CITYWALKS = {'cw_friends_001': {'citywalk_id': 'cw_friends_001',
                    'name': '国子监街-五道营胡同 Citywalk',
                    'category': 'citywalk',
                    'total_distance_km': 2.1,
                    'estimated_duration_min': 80,
                    'weather_sensitive': True,
                    'stops': [{'stop_id': 'cw_stop_001',
                               'name': '国子监街',
                               'address': '北京市东城区国子监街',
                               'stay_min': 20,
                               'facts_tags': [],
                               'place_features': ['cultural_street', 'hutong']},
                              {'stop_id': 'cw_stop_002',
                               'name': '孔庙和国子监博物馆外街区',
                               'address': '北京市东城区国子监街15号附近',
                               'stay_min': 20,
                               'facts_tags': [],
                               'place_features': ['culture']},
                              {'stop_id': 'cw_stop_003',
                               'name': '五道营胡同',
                               'address': '北京市东城区五道营胡同',
                               'stay_min': 40,
                               'facts_tags': [],
                               'place_features': ['cafe', 'shops']}],
                    'route_segments': [{'from_stop_id': 'cw_stop_001',
                                        'to_stop_id': 'cw_stop_002',
                                        'walk_distance_m': 450,
                                        'walk_time_min': 7},
                                       {'from_stop_id': 'cw_stop_002',
                                        'to_stop_id': 'cw_stop_003',
                                        'walk_distance_m': 850,
                                        'walk_time_min': 13}]},
 'cw_friends_002': {'citywalk_id': 'cw_friends_002',
                    'name': '朝阳公园轻 Citywalk',
                    'category': 'citywalk',
                    'total_distance_km': 1.8,
                    'estimated_duration_min': 70,
                    'weather_sensitive': True,
                    'stops': [{'stop_id': 'cy_stop_001',
                               'name': '朝阳公园南门',
                               'address': '北京市朝阳区朝阳公园南路',
                               'stay_min': 15,
                               'facts_tags': [],
                               'place_features': ['entrance', 'meeting_point']},
                              {'stop_id': 'cy_stop_002',
                               'name': '亮马河风情水岸',
                               'address': '北京市朝阳区亮马河沿线',
                               'stay_min': 35,
                               'facts_tags': [],
                               'place_features': ['walking']},
                              {'stop_id': 'cy_stop_003',
                               'name': '蓝色港湾',
                               'address': '北京市朝阳区朝阳公园路6号',
                               'stay_min': 20,
                               'facts_tags': [],
                               'place_features': ['dining', 'mall']}],
                    'route_segments': [{'from_stop_id': 'cy_stop_001',
                                        'to_stop_id': 'cy_stop_002',
                                        'walk_distance_m': 650,
                                        'walk_time_min': 10},
                                       {'from_stop_id': 'cy_stop_002',
                                        'to_stop_id': 'cy_stop_003',
                                        'walk_distance_m': 700,
                                        'walk_time_min': 11}]}}
