BASE_STATE = {'weather': {'location': '北京朝阳区望京',
             'condition': 'cloudy',
             'temperature_c': 28,
             'rain_level': 'none',
             'wind_level': 2,
             'risk_level': 'low',
             'updated_at': '2026-06-03T13:20:00'},
 'queues': {'rest_family_001': {'queue_tables': 8,
                                'estimated_wait_min': 18,
                                'can_take_number': True,
                                'status': 'normal',
                                'updated_at': '2026-06-03T13:20:00'},
            'rest_family_002': {'queue_tables': 4,
                                'estimated_wait_min': 12,
                                'can_take_number': True,
                                'status': 'normal',
                                'updated_at': '2026-06-03T13:20:00'},
            'rest_friend_001': {'queue_tables': 10,
                                'estimated_wait_min': 25,
                                'can_take_number': True,
                                'status': 'normal',
                                'updated_at': '2026-06-03T13:20:00'}},
 'bookings': {'act_friend_001': {'booking_required': True,
                                 'availability': 'limited',
                                 'available_slots': ['15:00'],
                                 'external_entry': {'type': 'wechat_official_account',
                                                    'name': '国家博物馆预约',
                                                    'url': 'mock://wechat/chnmuseum/reservation'},
                                 'risk_facts': ['热门场馆', '需要实名预约']}},
 'fulfillment': {},
 'watches': {},
 'events': [],
 'protected_nodes': [],
 'scenario_script': {'purpose': '给大模型事件模拟器使用的动态环境规则。Mock API 只应用事件事实，不负责规划决策。',
                     'time_bands': [{'band': '13:30-15:00',
                                     'likely_events': ['亲子乐园余票减少', '国博可预约时段减少'],
                                     'severity_hint': 'low'},
                                    {'band': '15:30-17:30',
                                     'likely_events': ['餐厅排队上升', '商场周边打车耗时增加'],
                                     'severity_hint': 'medium'},
                                    {'band': '17:30-19:00',
                                     'likely_events': ['晚餐高峰排队暴增', '用户可能上报儿童疲劳'],
                                     'severity_hint': 'high'},
                                    {'band': 'rainy_afternoon',
                                     'likely_events': ['户外路线受降雨影响', '室内活动余量减少'],
                                     'severity_hint': 'high'}],
                     'event_types': ['queue_spike',
                                     'weather_heavy_rain',
                                     'booking_full',
                                     'traffic_delay',
                                     'activity_capacity_low',
                                     'child_tired_user_reported'],
                     'guardrails': ['不要生成真实支付成功事件',
                                    '不要替用户确认购买或取消',
                                    '只模拟事实变化，不输出最终行程决策',
                                    '涉及儿童疲劳等主观状态时必须标记为 user_reported 或 assumed_low_confidence']}}
