POIS = [{'poi_id': 'act_family_001',
  'type': 'activity',
  'scenario': 'family',
  'name': '汤姆猫亲子乐园（易事达广场店）',
  'category': 'indoor_playground',
  'address': '北京市朝阳区易事达广场',
  'distance_km': 2.8,
  'open_status': 'open',
  'business_hours': '10:00-21:00',
  'booking_required': False,
  'availability': 'available',
  'available_slots': ['14:30', '15:00', '15:30'],
  'estimated_duration_min': 90,
  'facts_tags': [],
  'risk_facts': [],
  'external_entry': {'type': 'meituan_page', 'url': 'mock://meituan/activity/act_family_001'},
  'venue': {'environment': 'indoor'},
  'age_policy': {'min_age': 3, 'max_age': 10}},
 {'poi_id': 'act_family_002',
  'type': 'activity',
  'scenario': 'family',
  'name': 'Bingo Bay 亲子空间',
  'category': 'indoor_playground',
  'address': '北京市朝阳区甜水园北里12号院',
  'distance_km': 7.5,
  'open_status': 'open',
  'business_hours': '10:00-20:30',
  'booking_required': False,
  'availability': 'available',
  'available_slots': ['14:00', '15:00'],
  'estimated_duration_min': 80,
  'facts_tags': [],
  'risk_facts': [],
  'external_entry': {'type': 'meituan_page', 'url': 'mock://meituan/activity/act_family_002'},
  'venue': {'environment': 'indoor'},
  'age_policy': {'min_age': 3, 'max_age': 10}},
 {'poi_id': 'act_family_003',
  'type': 'activity',
  'scenario': 'family',
  'name': '彩虹树儿童绘本馆',
  'category': 'picture_book_library',
  'address': '北京市朝阳区望京商圈',
  'distance_km': 1.6,
  'open_status': 'open',
  'business_hours': '10:00-19:00',
  'booking_required': True,
  'availability': 'available',
  'available_slots': ['14:30', '16:00'],
  'estimated_duration_min': 70,
  'facts_tags': [],
  'risk_facts': [],
  'external_entry': {'type': 'wechat_official_account',
                     'url': 'mock://wechat/picture-book/reservation'},
  'venue': {'environment': 'indoor'},
  'activity_features': ['reading'],
  'age_policy': {'min_age': 3, 'max_age': 10}},
 {'poi_id': 'act_family_004',
  'type': 'activity',
  'scenario': 'family',
  'name': '中国电影博物馆',
  'category': 'children_science',
  'address': '北京市朝阳区南影路9号',
  'distance_km': 6.8,
  'open_status': 'open',
  'business_hours': '09:00-17:00',
  'booking_required': True,
  'availability': 'limited',
  'available_slots': ['14:00'],
  'estimated_duration_min': 90,
  'facts_tags': [],
  'risk_facts': ['17:00闭馆'],
  'external_entry': {'type': 'wechat_official_account', 'url': 'mock://wechat/cnfm/reservation'},
  'venue': {'environment': 'indoor'},
  'activity_features': ['film', 'science'],
  'age_policy': {'min_age': 3, 'max_age': 10},
  'booking_requirements': ['real_name_required']},
 {'poi_id': 'act_family_005',
  'type': 'activity',
  'scenario': 'family',
  'name': '国家自然博物馆',
  'category': 'children_science',
  'address': '北京市东城区天桥南大街126号',
  'distance_km': 14.5,
  'open_status': 'open',
  'business_hours': '09:00-17:00',
  'booking_required': True,
  'availability': 'limited',
  'available_slots': ['15:00'],
  'estimated_duration_min': 100,
  'facts_tags': [],
  'risk_facts': ['17:00闭馆'],
  'external_entry': {'type': 'wechat_official_account',
                     'url': 'mock://wechat/natural-museum/reservation'},
  'venue': {'environment': 'indoor'},
  'activity_features': ['science'],
  'age_policy': {'min_age': 3, 'max_age': 10},
  'booking_requirements': ['real_name_required']},
 {'poi_id': 'act_friend_001',
  'type': 'activity',
  'scenario': 'friends',
  'name': '中国国家博物馆',
  'category': 'museum',
  'address': '北京市东城区东长安街16号',
  'distance_km': 13.0,
  'open_status': 'open',
  'business_hours': '09:00-17:00',
  'booking_required': True,
  'availability': 'limited',
  'available_slots': ['15:00'],
  'estimated_duration_min': 120,
  'facts_tags': ['文化'],
  'risk_facts': ['需要实名预约'],
  'external_entry': {'type': 'wechat_official_account',
                     'url': 'mock://wechat/chnmuseum/reservation'},
  'venue': {'environment': 'indoor'},
  'booking_requirements': ['real_name_required']},
 {'poi_id': 'act_friend_002',
  'type': 'activity',
  'scenario': 'friends',
  'name': '朝阳公园 Citywalk',
  'category': 'citywalk',
  'citywalk_id': 'cw_friends_002',
  'address': '北京市朝阳区朝阳公园',
  'distance_km': 8.2,
  'open_status': 'open',
  'business_hours': '06:00-22:00',
  'booking_required': False,
  'availability': 'available',
  'available_slots': [],
  'estimated_duration_min': 90,
  'facts_tags': [],
  'risk_facts': [],
  'external_entry': {'type': 'map_page', 'url': 'mock://map/citywalk/cw_friends_002'},
  'venue': {'environment': 'outdoor'}},
 {'poi_id': 'act_friend_003',
  'type': 'activity',
  'scenario': 'friends',
  'name': '国子监街-五道营胡同 Citywalk',
  'category': 'citywalk',
  'citywalk_id': 'cw_friends_001',
  'address': '北京市东城区国子监街',
  'distance_km': 10.6,
  'open_status': 'open',
  'business_hours': '全天',
  'booking_required': False,
  'availability': 'available',
  'available_slots': [],
  'estimated_duration_min': 80,
  'facts_tags': [],
  'risk_facts': [],
  'external_entry': {'type': 'map_page', 'url': 'mock://map/citywalk/cw_friends_001'},
  'venue': {'environment': 'outdoor'},
  'activity_features': ['cafes_and_shops', 'hutong']},
 {'poi_id': 'act_friend_004',
  'type': 'activity',
  'scenario': 'friends',
  'name': '三国游艺·桌游文化馆',
  'category': 'board_game',
  'address': '北京市朝阳区望京商圈',
  'distance_km': 2.4,
  'open_status': 'open',
  'business_hours': '12:00-23:30',
  'booking_required': False,
  'availability': 'available',
  'available_slots': [],
  'estimated_duration_min': 120,
  'facts_tags': [],
  'risk_facts': [],
  'external_entry': {'type': 'meituan_page', 'url': 'mock://meituan/activity/act_friend_004'},
  'venue': {'environment': 'indoor'}},
 {'poi_id': 'act_friend_005',
  'type': 'activity',
  'scenario': 'friends',
  'name': '今日美术馆',
  'category': 'exhibition',
  'address': '北京市朝阳区百子湾路32号苹果社区4号楼',
  'distance_km': 11.2,
  'open_status': 'open',
  'business_hours': '10:00-18:00',
  'booking_required': False,
  'availability': 'available',
  'available_slots': [],
  'estimated_duration_min': 90,
  'facts_tags': [],
  'risk_facts': [],
  'external_entry': {'type': 'meituan_page', 'url': 'mock://meituan/exhibition/act_friend_005'},
  'venue': {'environment': 'indoor'},
  'activity_features': ['exhibition']},
 {'poi_id': 'act_friend_006',
  'type': 'activity',
  'scenario': 'friends',
  'name': 'MAO LiveHouse（华熙LIVE·五棵松店）',
  'category': 'livehouse',
  'address': '北京市海淀区复兴路69号华熙LIVE',
  'distance_km': 22.0,
  'open_status': 'open',
  'business_hours': '18:00-23:00',
  'booking_required': True,
  'availability': 'available',
  'available_slots': ['20:00'],
  'estimated_duration_min': 120,
  'facts_tags': [],
  'risk_facts': [],
  'external_entry': {'type': 'ticket_page', 'url': 'mock://ticket/livehouse/act_friend_006'},
  'venue': {'environment': 'indoor'},
  'activity_features': ['livehouse']},
 {'poi_id': 'act_friend_007',
  'type': 'activity',
  'scenario': 'friends',
  'name': '蓝色港湾商场展览区',
  'category': 'mall_exhibition',
  'address': '北京市朝阳区朝阳公园路6号',
  'distance_km': 8.6,
  'open_status': 'open',
  'business_hours': '10:00-22:00',
  'booking_required': False,
  'availability': 'available',
  'available_slots': [],
  'estimated_duration_min': 70,
  'facts_tags': [],
  'risk_facts': [],
  'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_friend_007'},
  'venue': {'environment': 'indoor'},
  'activity_features': ['mall']},
 {'poi_id': 'rest_family_001',
  'type': 'restaurant',
  'scenario': 'family',
  'name': '花园简餐 Bistro（望京店）',
  'category': 'restaurant',
  'address': '北京市朝阳区望京商圈',
  'distance_km': 0.9,
  'cuisine': '轻食简餐',
  'avg_price': 95,
  'booking_required': False,
  'available_slots': ['17:30', '18:00'],
  'facts_tags': [],
  'risk_facts': [],
  'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_family_001'},
  'menu_features': ['light_food_options', 'low_oil_options'],
  'facilities': {'child_seat': True}},
 {'poi_id': 'rest_family_002',
  'type': 'restaurant',
  'scenario': 'family',
  'name': '亲子轻食餐厅（望京店）',
  'category': 'restaurant',
  'address': '北京市朝阳区望京SOHO附近',
  'distance_km': 0.7,
  'cuisine': '轻食',
  'avg_price': 88,
  'booking_required': False,
  'available_slots': ['17:20', '18:00'],
  'facts_tags': [],
  'risk_facts': [],
  'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_family_002'},
  'menu_features': ['light_food_options', 'low_oil_options'],
  'facilities': {'child_seat': True}},
 {'poi_id': 'rest_family_003',
  'type': 'restaurant',
  'scenario': 'family',
  'name': '清淡粤菜小馆',
  'category': 'restaurant',
  'address': '北京市朝阳区望京新城',
  'distance_km': 1.1,
  'cuisine': '粤菜',
  'avg_price': 120,
  'booking_required': True,
  'available_slots': ['17:40', '18:20'],
  'facts_tags': [],
  'risk_facts': [],
  'external_entry': {'type': 'meituan_reserve_page',
                     'url': 'mock://meituan/reserve/rest_family_003'},
  'menu_features': ['low_oil_options']},
 {'poi_id': 'rest_friend_001',
  'type': 'restaurant',
  'scenario': 'friends',
  'name': '创意 Bistro（望京店）',
  'category': 'restaurant',
  'address': '北京市朝阳区望京SOHO',
  'distance_km': 2.1,
  'cuisine': '西餐Bistro',
  'avg_price': 160,
  'booking_required': True,
  'available_slots': ['18:00', '18:30'],
  'facts_tags': [],
  'risk_facts': [],
  'external_entry': {'type': 'meituan_reserve_page',
                     'url': 'mock://meituan/reserve/rest_friend_001'}},
 {'poi_id': 'rest_friend_002',
  'type': 'restaurant',
  'scenario': 'friends',
  'name': '望京韩式烤肉',
  'category': 'restaurant',
  'address': '北京市朝阳区望京韩国城附近',
  'distance_km': 1.8,
  'cuisine': '烤肉',
  'avg_price': 135,
  'booking_required': False,
  'available_slots': ['18:00', '19:00'],
  'facts_tags': [],
  'risk_facts': [],
  'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_friend_002'}},
 {'poi_id': 'rest_friend_003',
  'type': 'restaurant',
  'scenario': 'friends',
  'name': '蓝港茶餐厅',
  'category': 'restaurant',
  'address': '北京市朝阳区蓝色港湾',
  'distance_km': 8.7,
  'cuisine': '茶餐厅',
  'avg_price': 90,
  'booking_required': False,
  'available_slots': ['18:30', '19:00'],
  'facts_tags': [],
  'risk_facts': [],
  'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_friend_003'},
  'location_features': ['mall']}]
