BASE_STATE = {'weather': {'location': '北京朝阳区望京',
             'condition': 'cloudy',
             'temperature_c': 28,
             'rain_level': 'none',
             'wind_level': 2,
             'risk_level': 'low',
             'updated_at': '2026-06-03T13:20:00'},
 'queues': {'rest_family_001': {'queue_tables': 8,  'estimated_wait_min': 18, 'can_take_number': True, 'status': 'normal', 'updated_at': '2026-06-03T13:20:00'},
            'rest_family_002': {'queue_tables': 4,  'estimated_wait_min': 12, 'can_take_number': True, 'status': 'normal', 'updated_at': '2026-06-03T13:20:00'},
            'rest_family_003': {'queue_tables': 3,  'estimated_wait_min': 8,  'can_take_number': True, 'status': 'normal', 'updated_at': '2026-06-03T13:20:00'},
            'rest_family_004': {'queue_tables': 15, 'estimated_wait_min': 35, 'can_take_number': True, 'status': 'normal', 'updated_at': '2026-06-03T13:20:00'},
            'rest_friend_001': {'queue_tables': 10, 'estimated_wait_min': 25, 'can_take_number': True, 'status': 'normal', 'updated_at': '2026-06-03T13:20:00'},
            'rest_friend_002': {'queue_tables': 6,  'estimated_wait_min': 15, 'can_take_number': True, 'status': 'normal', 'updated_at': '2026-06-03T13:20:00'},
            'rest_friend_003': {'queue_tables': 2,  'estimated_wait_min': 5,  'can_take_number': True, 'status': 'normal', 'updated_at': '2026-06-03T13:20:00'},
            'rest_friend_004': {'queue_tables': 12, 'estimated_wait_min': 30, 'can_take_number': True, 'status': 'normal', 'updated_at': '2026-06-03T13:20:00'},
            'rest_couple_001': {'queue_tables': 0,  'estimated_wait_min': 0,  'can_take_number': False,'status': 'normal', 'updated_at': '2026-06-03T13:20:00'},
            'rest_couple_002': {'queue_tables': 0,  'estimated_wait_min': 0,  'can_take_number': False,'status': 'normal', 'updated_at': '2026-06-03T13:20:00'},
            'rest_couple_003': {'queue_tables': 2,  'estimated_wait_min': 10, 'can_take_number': True, 'status': 'normal', 'updated_at': '2026-06-03T13:20:00'},
            'rest_both_001':   {'queue_tables': 7,  'estimated_wait_min': 20, 'can_take_number': True, 'status': 'normal', 'updated_at': '2026-06-03T13:20:00'}},
 'bookings': {'act_friend_001': {'booking_required': True,
                                 'availability': 'limited',
                                 'available_slots': ['15:00'],
                                 'external_entry': {'type': 'wechat_official_account',
                                                    'name': '国家博物馆预约',
                                                    'url': 'mock://wechat/chnmuseum/reservation'},
                                 'risk_facts': ['热门场馆', '需要实名预约']}},
 'fulfillment': {},
 'watches': {},
 'events': [],
 'protected_nodes': [],
 'taxi_pool': [
     {'plate_no': '京A·3F782', 'driver': '王师傅', 'car_model': '比亚迪汉EV', 'rating': 4.9},
     {'plate_no': '京B·8K291', 'driver': '李师傅', 'car_model': '特斯拉Model 3', 'rating': 4.8},
     {'plate_no': '京C·5H436', 'driver': '张师傅', 'car_model': '大众朗逸', 'rating': 4.7},
     {'plate_no': '京G·2M917', 'driver': '刘师傅', 'car_model': '丰田凯美瑞', 'rating': 4.9},
     {'plate_no': '京A·99F45', 'driver': '陈师傅', 'car_model': '滴滴专车·宝来', 'rating': 4.6},
     {'plate_no': '京B·73D28', 'driver': '赵师傅', 'car_model': '本田雅阁', 'rating': 4.8},
     {'plate_no': '京D·61K90', 'driver': '孙师傅', 'car_model': '比亚迪秦PLUS', 'rating': 4.7},
     {'plate_no': '京H·24Z55', 'driver': '周师傅', 'car_model': '大众迈腾', 'rating': 4.9},
 ],
 'scenario_script': {'purpose': '给大模型事件模拟器使用的动态环境规则。Mock API 只应用事件事实，不负责规划决策。',
                     'time_bands': [{'band': '13:30-15:00',
                                     'likely_events': ['亲子乐园余票减少', '国博可预约时段减少'],
                                     'severity_hint': 'low'},
                                    {'band': '15:30-17:30',
                                     'likely_events': ['餐厅排队上升', '商场周边打车耗时增加'],
                                     'severity_hint': 'medium'},
                                    {'band': '17:30-19:00',
                                     'likely_events': ['晚餐高峰排队暴增', '用户可能上报儿童疲劳'],
                                     'severity_hint': 'high'},
                                    {'band': 'rainy_afternoon',
                                     'likely_events': ['户外路线受降雨影响', '室内活动余量减少'],
                                     'severity_hint': 'high'}],
                     'event_types': ['queue_spike',
                                     'weather_heavy_rain',
                                     'booking_full',
                                     'traffic_delay',
                                     'activity_capacity_low',
                                     'child_tired_user_reported'],
                     'guardrails': ['不要生成真实支付成功事件',
                                    '不要替用户确认购买或取消',
                                    '只模拟事实变化，不输出最终行程决策',
                                    '涉及儿童疲劳等主观状态时必须标记为 user_reported 或 assumed_low_confidence']}}
