POIS = [
  # ─────────────────── FAMILY ACTIVITIES ────────────────────────────
  {'poi_id': 'act_family_001',
   'type': 'activity', 'scenario': 'family',
   'name': '汤姆猫亲子乐园（易事达广场店）',
   'category': 'indoor_playground',
   'address': '北京市朝阳区易事达广场',
   'distance_km': 2.8, 'open_status': 'open',
   'business_hours': '10:00-21:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': ['14:30', '15:00', '15:30'],
   'estimated_duration_min': 90,
   'rating': 4.6,
   'tags': ['室内', '亲子', '适合3-10岁', '无需预约'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_page', 'url': 'mock://meituan/activity/act_family_001'},
   'venue': {'environment': 'indoor'},
   'age_policy': {'min_age': 3, 'max_age': 10}},

  {'poi_id': 'act_family_002',
   'type': 'activity', 'scenario': 'family',
   'name': 'Bingo Bay 亲子空间',
   'category': 'indoor_playground',
   'address': '北京市朝阳区甜水园北里12号院',
   'distance_km': 7.5, 'open_status': 'open',
   'business_hours': '10:00-20:30',
   'booking_required': False, 'availability': 'available',
   'available_slots': ['14:00', '15:00'],
   'estimated_duration_min': 80,
   'rating': 4.4,
   'tags': ['室内', '亲子', '软体乐园', '无需预约'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_page', 'url': 'mock://meituan/activity/act_family_002'},
   'venue': {'environment': 'indoor'},
   'age_policy': {'min_age': 3, 'max_age': 10}},

  {'poi_id': 'act_family_003',
   'type': 'activity', 'scenario': 'family',
   'name': '彩虹树儿童绘本馆',
   'category': 'picture_book_library',
   'address': '北京市朝阳区望京商圈',
   'distance_km': 1.6, 'open_status': 'open',
   'business_hours': '10:00-19:00',
   'booking_required': True, 'availability': 'available',
   'available_slots': ['14:30', '16:00'],
   'estimated_duration_min': 70,
   'rating': 4.8,
   'tags': ['室内', '亲子', '阅读', '安静', '需预约'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'wechat_official_account', 'url': 'mock://wechat/picture-book/reservation'},
   'venue': {'environment': 'indoor'},
   'activity_features': ['reading'],
   'age_policy': {'min_age': 3, 'max_age': 10}},

  {'poi_id': 'act_family_004',
   'type': 'activity', 'scenario': 'family',
   'name': '中国电影博物馆',
   'category': 'children_science',
   'address': '北京市朝阳区南影路9号',
   'distance_km': 6.8, 'open_status': 'open',
   'business_hours': '09:00-17:00',
   'booking_required': True, 'availability': 'limited',
   'available_slots': ['14:00'],
   'estimated_duration_min': 90,
   'rating': 4.5,
   'tags': ['室内', '科普', '电影文化', '需实名预约', '17点闭馆'],
   'facts_tags': [], 'risk_facts': ['17:00闭馆'],
   'external_entry': {'type': 'wechat_official_account', 'url': 'mock://wechat/cnfm/reservation'},
   'venue': {'environment': 'indoor'},
   'activity_features': ['film', 'science'],
   'age_policy': {'min_age': 3, 'max_age': 10},
   'booking_requirements': ['real_name_required']},

  {'poi_id': 'act_family_005',
   'type': 'activity', 'scenario': 'family',
   'name': '国家自然博物馆',
   'category': 'children_science',
   'address': '北京市东城区天桥南大街126号',
   'distance_km': 14.5, 'open_status': 'open',
   'business_hours': '09:00-17:00',
   'booking_required': True, 'availability': 'limited',
   'available_slots': ['15:00'],
   'estimated_duration_min': 100,
   'rating': 4.7,
   'tags': ['室内', '科普', '自然', '需实名预约', '较远'],
   'facts_tags': [], 'risk_facts': ['17:00闭馆'],
   'external_entry': {'type': 'wechat_official_account', 'url': 'mock://wechat/natural-museum/reservation'},
   'venue': {'environment': 'indoor'},
   'activity_features': ['science'],
   'age_policy': {'min_age': 3, 'max_age': 10},
   'booking_requirements': ['real_name_required']},

  {'poi_id': 'act_family_006',
   'type': 'activity', 'scenario': 'family',
   'name': '望京公园儿童游乐区',
   'category': 'outdoor_park',
   'address': '北京市朝阳区望京公园',
   'distance_km': 1.2, 'open_status': 'open',
   'business_hours': '06:00-21:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 75,
   'rating': 4.2,
   'tags': ['户外', '亲子', '免费', '无需预约', '适合跑跳'],
   'facts_tags': [], 'risk_facts': ['天气不好影响体验'],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_family_006'},
   'venue': {'environment': 'outdoor'},
   'age_policy': {'min_age': 2, 'max_age': 12}},

  # ─────────────────── FRIENDS ACTIVITIES ───────────────────────────
  {'poi_id': 'act_friend_001',
   'type': 'activity', 'scenario': 'friends',
   'name': '中国国家博物馆',
   'category': 'museum',
   'address': '北京市东城区东长安街16号',
   'distance_km': 13.0, 'open_status': 'open',
   'business_hours': '09:00-17:00',
   'booking_required': True, 'availability': 'limited',
   'available_slots': ['15:00'],
   'estimated_duration_min': 120,
   'rating': 4.9,
   'tags': ['室内', '文化', '历史', '需实名预约', '17点闭馆'],
   'facts_tags': ['文化'], 'risk_facts': ['需要实名预约'],
   'external_entry': {'type': 'wechat_official_account', 'url': 'mock://wechat/chnmuseum/reservation'},
   'venue': {'environment': 'indoor'},
   'booking_requirements': ['real_name_required']},

  {'poi_id': 'act_friend_002',
   'type': 'activity', 'scenario': 'friends',
   'name': '朝阳公园 Citywalk',
   'category': 'citywalk',
   'citywalk_id': 'cw_friends_002',
   'address': '北京市朝阳区朝阳公园',
   'distance_km': 8.2, 'open_status': 'open',
   'business_hours': '06:00-22:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 90,
   'rating': 4.5,
   'tags': ['户外', '打卡', '骑行', 'Citywalk', '活力'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/citywalk/cw_friends_002'},
   'venue': {'environment': 'outdoor'}},

  {'poi_id': 'act_friend_003',
   'type': 'activity', 'scenario': 'friends',
   'name': '国子监街-五道营胡同 Citywalk',
   'category': 'citywalk',
   'citywalk_id': 'cw_friends_001',
   'address': '北京市东城区国子监街',
   'distance_km': 10.6, 'open_status': 'open',
   'business_hours': '全天',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 80,
   'rating': 4.7,
   'tags': ['户外', '胡同', 'Citywalk', '文艺', '咖啡馆'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/citywalk/cw_friends_001'},
   'venue': {'environment': 'outdoor'},
   'activity_features': ['cafes_and_shops', 'hutong']},

  {'poi_id': 'act_friend_004',
   'type': 'activity', 'scenario': 'friends',
   'name': '三国游艺·桌游文化馆',
   'category': 'board_game',
   'address': '北京市朝阳区望京商圈',
   'distance_km': 2.4, 'open_status': 'open',
   'business_hours': '12:00-23:30',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 120,
   'rating': 4.6,
   'tags': ['室内', '桌游', '休闲', '社交', '无需预约'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_page', 'url': 'mock://meituan/activity/act_friend_004'},
   'venue': {'environment': 'indoor'}},

  {'poi_id': 'act_friend_005',
   'type': 'activity', 'scenario': 'friends',
   'name': '今日美术馆',
   'category': 'exhibition',
   'address': '北京市朝阳区百子湾路32号苹果社区4号楼',
   'distance_km': 11.2, 'open_status': 'open',
   'business_hours': '10:00-18:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 90,
   'rating': 4.5,
   'tags': ['室内', '艺术', '展览', '打卡', '文艺'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_page', 'url': 'mock://meituan/exhibition/act_friend_005'},
   'venue': {'environment': 'indoor'},
   'activity_features': ['exhibition']},

  {'poi_id': 'act_friend_006',
   'type': 'activity', 'scenario': 'friends',
   'name': 'MAO LiveHouse（华熙LIVE·五棵松店）',
   'category': 'livehouse',
   'address': '北京市海淀区复兴路69号华熙LIVE',
   'distance_km': 22.0, 'open_status': 'open',
   'business_hours': '18:00-23:00',
   'booking_required': True, 'availability': 'available',
   'available_slots': ['20:00'],
   'estimated_duration_min': 120,
   'rating': 4.8,
   'tags': ['室内', 'LiveHouse', '夜间', '演出', '需提前购票'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'ticket_page', 'url': 'mock://ticket/livehouse/act_friend_006'},
   'venue': {'environment': 'indoor'},
   'activity_features': ['livehouse']},

  {'poi_id': 'act_friend_007',
   'type': 'activity', 'scenario': 'friends',
   'name': '蓝色港湾商场展览区',
   'category': 'mall_exhibition',
   'address': '北京市朝阳区朝阳公园路6号',
   'distance_km': 8.6, 'open_status': 'open',
   'business_hours': '10:00-22:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 70,
   'rating': 4.3,
   'tags': ['室内', '购物', '展览', '网红打卡', '无需预约'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_friend_007'},
   'venue': {'environment': 'indoor'},
   'activity_features': ['mall']},

  # ─────────────────── COUPLE ACTIVITIES ────────────────────────────
  {'poi_id': 'act_couple_001',
   'type': 'activity', 'scenario': 'couple',
   'name': '望京·朝花夕拾 Citywalk',
   'category': 'citywalk',
   'address': '北京市朝阳区望京花园街区',
   'distance_km': 1.0, 'open_status': 'open',
   'business_hours': '全天',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 80,
   'rating': 4.6,
   'tags': ['户外', '散步', '情侣', 'Citywalk', '轻松浪漫'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/citywalk/act_couple_001'},
   'venue': {'environment': 'outdoor'}},

  {'poi_id': 'act_couple_002',
   'type': 'activity', 'scenario': 'couple',
   'name': 'M WOODS 木木美术馆',
   'category': 'exhibition',
   'address': '北京市朝阳区798艺术区',
   'distance_km': 9.5, 'open_status': 'open',
   'business_hours': '11:00-19:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 90,
   'rating': 4.8,
   'tags': ['室内', '当代艺术', '情侣打卡', '文艺', '网红'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_page', 'url': 'mock://meituan/exhibition/act_couple_002'},
   'venue': {'environment': 'indoor'},
   'activity_features': ['exhibition', 'contemporary_art']},

  {'poi_id': 'act_couple_003',
   'type': 'activity', 'scenario': 'couple',
   'name': '尤伦斯当代艺术中心（UCCA）',
   'category': 'exhibition',
   'address': '北京市朝阳区酒仙桥路4号798艺术区',
   'distance_km': 11.8, 'open_status': 'open',
   'business_hours': '10:00-19:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 100,
   'rating': 4.9,
   'tags': ['室内', '当代艺术', '情侣', '高端文艺', '798'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_page', 'url': 'mock://meituan/exhibition/act_couple_003'},
   'venue': {'environment': 'indoor'},
   'activity_features': ['exhibition']},

  {'poi_id': 'act_couple_004',
   'type': 'activity', 'scenario': 'couple',
   'name': '朝阳公园湖边漫步',
   'category': 'outdoor_park',
   'address': '北京市朝阳区朝阳公园南路',
   'distance_km': 8.0, 'open_status': 'open',
   'business_hours': '06:00-21:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 75,
   'rating': 4.5,
   'tags': ['户外', '湖景', '情侣散步', '轻松', '免费'],
   'facts_tags': [], 'risk_facts': ['天气不好影响体验'],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_couple_004'},
   'venue': {'environment': 'outdoor'}},

  # ─────────────────── UNIVERSAL / BOTH ACTIVITIES ──────────────────
  {'poi_id': 'act_both_001',
   'type': 'activity', 'scenario': 'both',
   'name': '北京SKP-S 沉浸式商场体验',
   'category': 'mall_exhibition',
   'address': '北京市朝阳区建国路87号',
   'distance_km': 11.0, 'open_status': 'open',
   'business_hours': '10:00-22:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 80,
   'rating': 4.7,
   'tags': ['室内', '购物', '艺术装置', '打卡', '全年龄'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_both_001'},
   'venue': {'environment': 'indoor'}},

  {'poi_id': 'act_both_002',
   'type': 'activity', 'scenario': 'both',
   'name': '望京三里屯太古里街区逛逛',
   'category': 'citywalk',
   'address': '北京市朝阳区三里屯路',
   'distance_km': 6.5, 'open_status': 'open',
   'business_hours': '10:00-23:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 70,
   'rating': 4.4,
   'tags': ['户外', '逛街', '购物', '轻松', '全年龄'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_both_002'},
   'venue': {'environment': 'outdoor'}},

  # ─────────────────── FAMILY RESTAURANTS ───────────────────────────
  {'poi_id': 'rest_family_001',
   'type': 'restaurant', 'scenario': 'family',
   'name': '花园简餐 Bistro（望京店）',
   'category': 'restaurant',
   'address': '北京市朝阳区望京商圈',
   'distance_km': 0.9,
   'cuisine': '轻食简餐',
   'avg_price': 95,
   'rating': 4.5,
   'tags': ['轻食', '亲子友好', '儿童椅', '清淡健康'],
   'booking_required': False,
   'available_slots': ['17:30', '18:00'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_family_001'},
   'menu_features': ['light_food_options', 'low_oil_options'],
   'facilities': {'child_seat': True}},

  {'poi_id': 'rest_family_002',
   'type': 'restaurant', 'scenario': 'family',
   'name': '亲子轻食餐厅（望京店）',
   'category': 'restaurant',
   'address': '北京市朝阳区望京SOHO附近',
   'distance_km': 0.7,
   'cuisine': '轻食',
   'avg_price': 88,
   'rating': 4.4,
   'tags': ['轻食', '亲子友好', '儿童椅', '价格亲民'],
   'booking_required': False,
   'available_slots': ['17:20', '18:00'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_family_002'},
   'menu_features': ['light_food_options', 'low_oil_options'],
   'facilities': {'child_seat': True}},

  {'poi_id': 'rest_family_003',
   'type': 'restaurant', 'scenario': 'family',
   'name': '清淡粤菜小馆',
   'category': 'restaurant',
   'address': '北京市朝阳区望京新城',
   'distance_km': 1.1,
   'cuisine': '粤菜',
   'avg_price': 120,
   'rating': 4.6,
   'tags': ['粤菜', '清淡', '适合老人儿童', '需预约'],
   'booking_required': True,
   'available_slots': ['17:40', '18:20'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_reserve_page', 'url': 'mock://meituan/reserve/rest_family_003'},
   'menu_features': ['low_oil_options'],
   'facilities': {'child_seat': True}},

  {'poi_id': 'rest_family_004',
   'type': 'restaurant', 'scenario': 'family',
   'name': '海底捞火锅（望京店）',
   'category': 'restaurant',
   'address': '北京市朝阳区望京SOHO',
   'distance_km': 1.5,
   'cuisine': '火锅',
   'avg_price': 110,
   'rating': 4.7,
   'tags': ['火锅', '亲子', '儿童椅', '人气高', '适合聚餐'],
   'booking_required': False,
   'available_slots': ['17:00', '18:00', '19:00'],
   'facts_tags': [], 'risk_facts': ['晚餐高峰排队较长'],
   'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_family_004'},
   'menu_features': [],
   'facilities': {'child_seat': True}},

  # ─────────────────── FRIENDS RESTAURANTS ──────────────────────────
  {'poi_id': 'rest_friend_001',
   'type': 'restaurant', 'scenario': 'friends',
   'name': '创意 Bistro（望京店）',
   'category': 'restaurant',
   'address': '北京市朝阳区望京SOHO',
   'distance_km': 2.1,
   'cuisine': '西餐Bistro',
   'avg_price': 160,
   'rating': 4.6,
   'tags': ['西餐', '高颜值', '打卡', '适合聚会', '需预约'],
   'booking_required': True,
   'available_slots': ['18:00', '18:30'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_reserve_page', 'url': 'mock://meituan/reserve/rest_friend_001'},
   'menu_features': [],
   'facilities': {}},

  {'poi_id': 'rest_friend_002',
   'type': 'restaurant', 'scenario': 'friends',
   'name': '望京韩式烤肉',
   'category': 'restaurant',
   'address': '北京市朝阳区望京韩国城附近',
   'distance_km': 1.8,
   'cuisine': '烤肉',
   'avg_price': 135,
   'rating': 4.5,
   'tags': ['烤肉', '韩料', '朋友聚餐', '热闹', '无需预约'],
   'booking_required': False,
   'available_slots': ['18:00', '19:00'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_friend_002'},
   'menu_features': [],
   'facilities': {}},

  {'poi_id': 'rest_friend_003',
   'type': 'restaurant', 'scenario': 'friends',
   'name': '蓝港茶餐厅',
   'category': 'restaurant',
   'address': '北京市朝阳区蓝色港湾',
   'distance_km': 8.7,
   'cuisine': '茶餐厅',
   'avg_price': 90,
   'rating': 4.3,
   'tags': ['茶餐厅', '港式', '休闲', '价格适中'],
   'booking_required': False,
   'available_slots': ['18:30', '19:00'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_friend_003'},
   'location_features': ['mall'],
   'facilities': {}},

  {'poi_id': 'rest_friend_004',
   'type': 'restaurant', 'scenario': 'friends',
   'name': '朝阳大悦城潮汕牛肉火锅',
   'category': 'restaurant',
   'address': '北京市朝阳区大悦城',
   'distance_km': 12.5,
   'cuisine': '潮汕火锅',
   'avg_price': 150,
   'rating': 4.8,
   'tags': ['火锅', '潮汕', '高口碑', '适合多人', '人气高'],
   'booking_required': True,
   'available_slots': ['18:00', '19:00'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_reserve_page', 'url': 'mock://meituan/reserve/rest_friend_004'},
   'menu_features': [],
   'facilities': {}},

  # ─────────────────── COUPLE RESTAURANTS ───────────────────────────
  {'poi_id': 'rest_couple_001',
   'type': 'restaurant', 'scenario': 'couple',
   'name': '望京·囍堂日料（情侣套餐）',
   'category': 'restaurant',
   'address': '北京市朝阳区望京SOHO A座',
   'distance_km': 1.3,
   'cuisine': '日料',
   'avg_price': 280,
   'rating': 4.8,
   'tags': ['日料', '浪漫', '情侣', '私密', '推荐提前预约'],
   'booking_required': True,
   'available_slots': ['18:00', '18:30', '19:00'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_reserve_page', 'url': 'mock://meituan/reserve/rest_couple_001'},
   'menu_features': [],
   'facilities': {}},

  {'poi_id': 'rest_couple_002',
   'type': 'restaurant', 'scenario': 'couple',
   'name': '798意式餐厅（烛光晚餐）',
   'category': 'restaurant',
   'address': '北京市朝阳区798艺术区',
   'distance_km': 10.2,
   'cuisine': '意大利菜',
   'avg_price': 220,
   'rating': 4.7,
   'tags': ['西餐', '浪漫', '烛光', '情侣首选', '798'],
   'booking_required': True,
   'available_slots': ['18:30', '19:00'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_reserve_page', 'url': 'mock://meituan/reserve/rest_couple_002'},
   'menu_features': [],
   'facilities': {}},

  {'poi_id': 'rest_couple_003',
   'type': 'restaurant', 'scenario': 'couple',
   'name': '望京屋顶酒吧 Skyline Rooftop',
   'category': 'restaurant',
   'address': '北京市朝阳区望京国际商业中心顶楼',
   'distance_km': 2.0,
   'cuisine': '酒吧餐厅',
   'avg_price': 180,
   'rating': 4.6,
   'tags': ['酒吧', '屋顶', '夜景', '情侣', '鸡尾酒'],
   'booking_required': False,
   'available_slots': ['17:00', '18:00', '19:00'],
   'facts_tags': [], 'risk_facts': ['需年满18周岁'],
   'external_entry': {'type': 'meituan_reserve_page', 'url': 'mock://meituan/reserve/rest_couple_003'},
   'menu_features': [],
   'facilities': {}},

  # ─────────────────── UNIVERSAL RESTAURANTS ────────────────────────
  {'poi_id': 'rest_both_001',
   'type': 'restaurant', 'scenario': 'both',
   'name': '望京北京烤鸭（四季民福附近）',
   'category': 'restaurant',
   'address': '北京市朝阳区望京',
   'distance_km': 3.2,
   'cuisine': '北京菜',
   'avg_price': 130,
   'rating': 4.7,
   'tags': ['北京烤鸭', '北京特色', '适合所有人', '打卡必吃'],
   'booking_required': False,
   'available_slots': ['17:30', '18:00', '18:30'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_both_001'},
   'menu_features': [],
   'facilities': {'child_seat': True}},

  # ═══════════════════ ADDITIONAL ACTIVITIES (30) ═══════════════════

  # ── Family Activities 007-013 ──────────────────────────────────────
  {'poi_id': 'act_family_007',
   'type': 'activity', 'scenario': 'family',
   'name': '北京天文馆',
   'category': 'children_science',
   'address': '北京市海淀区西直门外大街138号',
   'distance_km': 15.0, 'open_status': 'open',
   'business_hours': '09:30-16:30',
   'booking_required': True, 'availability': 'available',
   'available_slots': ['10:00', '13:30', '15:00'],
   'estimated_duration_min': 100,
   'rating': 4.7,
   'tags': ['室内', '科普', '天文', '亲子', '需预约', '球幕影院'],
   'facts_tags': [], 'risk_facts': ['16:30闭馆，请提前离开'],
   'external_entry': {'type': 'wechat_official_account', 'url': 'mock://wechat/bjplanetarium/reservation'},
   'venue': {'environment': 'indoor'},
   'age_policy': {'min_age': 4, 'max_age': 14}},

  {'poi_id': 'act_family_008',
   'type': 'activity', 'scenario': 'family',
   'name': '北京动物园',
   'category': 'outdoor_park',
   'address': '北京市西城区西直门外大街137号',
   'distance_km': 14.5, 'open_status': 'open',
   'business_hours': '07:30-17:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 150,
   'rating': 4.5,
   'tags': ['户外', '亲子', '动物', '熊猫', '适合全家'],
   'facts_tags': [], 'risk_facts': ['17:00闭馆', '周末人较多'],
   'external_entry': {'type': 'meituan_page', 'url': 'mock://meituan/activity/act_family_008'},
   'venue': {'environment': 'outdoor'},
   'age_policy': {'min_age': 2, 'max_age': 14}},

  {'poi_id': 'act_family_009',
   'type': 'activity', 'scenario': 'family',
   'name': '中国科学技术馆',
   'category': 'children_science',
   'address': '北京市朝阳区北辰东路5号',
   'distance_km': 7.8, 'open_status': 'open',
   'business_hours': '09:30-17:00',
   'booking_required': True, 'availability': 'available',
   'available_slots': ['09:30', '13:00'],
   'estimated_duration_min': 150,
   'rating': 4.8,
   'tags': ['室内', '科技馆', '互动', '亲子', '需实名预约'],
   'facts_tags': [], 'risk_facts': ['需实名预约', '17点闭馆'],
   'external_entry': {'type': 'wechat_official_account', 'url': 'mock://wechat/cstm/reservation'},
   'venue': {'environment': 'indoor'},
   'age_policy': {'min_age': 4, 'max_age': 14},
   'booking_requirements': ['real_name_required']},

  {'poi_id': 'act_family_010',
   'type': 'activity', 'scenario': 'family',
   'name': '北京欢乐谷',
   'category': 'indoor_playground',
   'address': '北京市朝阳区东四环小武基路',
   'distance_km': 10.5, 'open_status': 'open',
   'business_hours': '09:30-20:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 180,
   'rating': 4.4,
   'tags': ['户外', '游乐园', '刺激项目', '亲子', '全天玩'],
   'facts_tags': [], 'risk_facts': ['身高限制部分项目', '节假日排队较长'],
   'external_entry': {'type': 'meituan_page', 'url': 'mock://meituan/activity/act_family_010'},
   'venue': {'environment': 'outdoor'},
   'age_policy': {'min_age': 4, 'max_age': 14}},

  {'poi_id': 'act_family_011',
   'type': 'activity', 'scenario': 'family',
   'name': '北京海洋馆',
   'category': 'children_science',
   'address': '北京市海淀区北京动物园内',
   'distance_km': 14.5, 'open_status': 'open',
   'business_hours': '09:00-17:30',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 120,
   'rating': 4.5,
   'tags': ['室内', '海洋', '水族馆', '亲子', '鱼类展示'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_page', 'url': 'mock://meituan/activity/act_family_011'},
   'venue': {'environment': 'indoor'},
   'age_policy': {'min_age': 2, 'max_age': 12}},

  {'poi_id': 'act_family_012',
   'type': 'activity', 'scenario': 'family',
   'name': '西贝亲子烘焙体验馆',
   'category': 'indoor_playground',
   'address': '北京市朝阳区望京凯德MALL',
   'distance_km': 1.8, 'open_status': 'open',
   'business_hours': '10:00-21:00',
   'booking_required': True, 'availability': 'available',
   'available_slots': ['10:30', '14:00', '15:30'],
   'estimated_duration_min': 90,
   'rating': 4.6,
   'tags': ['室内', '亲子烘焙', '动手体验', '需预约', '适合3-10岁'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_page', 'url': 'mock://meituan/activity/act_family_012'},
   'venue': {'environment': 'indoor'},
   'age_policy': {'min_age': 3, 'max_age': 10}},

  {'poi_id': 'act_family_013',
   'type': 'activity', 'scenario': 'family',
   'name': '北京植物园（樱桃沟区）',
   'category': 'outdoor_park',
   'address': '北京市海淀区香山南路',
   'distance_km': 22.0, 'open_status': 'open',
   'business_hours': '07:00-19:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 120,
   'rating': 4.6,
   'tags': ['户外', '植物园', '自然', '亲子', '春季赏花'],
   'facts_tags': [], 'risk_facts': ['天气影响体验', '较远需打车'],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_family_013'},
   'venue': {'environment': 'outdoor'},
   'age_policy': {'min_age': 2, 'max_age': 14}},

  # ── Friends Activities 008-016 ─────────────────────────────────────
  {'poi_id': 'act_friend_008',
   'type': 'activity', 'scenario': 'friends',
   'name': '798艺术区游览',
   'category': 'exhibition',
   'address': '北京市朝阳区酒仙桥路4号',
   'distance_km': 11.0, 'open_status': 'open',
   'business_hours': '10:00-18:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 120,
   'rating': 4.7,
   'tags': ['户外', '艺术', '工业风', '打卡', '画廊', '文创'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_friend_008'},
   'venue': {'environment': 'outdoor'}},

  {'poi_id': 'act_friend_009',
   'type': 'activity', 'scenario': 'friends',
   'name': '南锣鼓巷-烟袋斜街 Citywalk',
   'category': 'citywalk',
   'address': '北京市东城区南锣鼓巷',
   'distance_km': 12.5, 'open_status': 'open',
   'business_hours': '全天',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 100,
   'rating': 4.6,
   'tags': ['户外', '胡同', 'Citywalk', '文艺', '小吃', '打卡'],
   'facts_tags': [], 'risk_facts': ['节假日人多'],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/citywalk/act_friend_009'},
   'venue': {'environment': 'outdoor'}},

  {'poi_id': 'act_friend_010',
   'type': 'activity', 'scenario': 'friends',
   'name': '故宫博物院（午门-神武门）',
   'category': 'museum',
   'address': '北京市东城区景山前街4号',
   'distance_km': 13.8, 'open_status': 'open',
   'business_hours': '08:30-17:00',
   'booking_required': True, 'availability': 'limited',
   'available_slots': ['08:30', '10:00'],
   'estimated_duration_min': 150,
   'rating': 4.9,
   'tags': ['室内', '世界遗产', '历史', '文化', '必去', '需实名预约'],
   'facts_tags': ['文化', '历史'], 'risk_facts': ['需实名预约', '17点闭馆'],
   'external_entry': {'type': 'wechat_official_account', 'url': 'mock://wechat/gugong/reservation'},
   'venue': {'environment': 'outdoor'},
   'booking_requirements': ['real_name_required']},

  {'poi_id': 'act_friend_011',
   'type': 'activity', 'scenario': 'friends',
   'name': '天坛公园',
   'category': 'outdoor_park',
   'address': '北京市东城区天坛东里7号',
   'distance_km': 15.2, 'open_status': 'open',
   'business_hours': '06:00-22:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 100,
   'rating': 4.7,
   'tags': ['户外', '世界遗产', '历史', '文化', '公园', '古建筑'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_page', 'url': 'mock://meituan/activity/act_friend_011'},
   'venue': {'environment': 'outdoor'}},

  {'poi_id': 'act_friend_012',
   'type': 'activity', 'scenario': 'friends',
   'name': '奥林匹克公园（鸟巢水立方）',
   'category': 'outdoor_park',
   'address': '北京市朝阳区国家奥林匹克公园',
   'distance_km': 8.5, 'open_status': 'open',
   'business_hours': '06:00-22:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 90,
   'rating': 4.6,
   'tags': ['户外', '地标', '奥运', '打卡', '夜景', '免费'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_friend_012'},
   'venue': {'environment': 'outdoor'}},

  {'poi_id': 'act_friend_013',
   'type': 'activity', 'scenario': 'friends',
   'name': '后海酒吧街夜游',
   'category': 'citywalk',
   'address': '北京市西城区后海北沿',
   'distance_km': 12.0, 'open_status': 'open',
   'business_hours': '14:00-02:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 90,
   'rating': 4.5,
   'tags': ['户外', '夜生活', '酒吧', '湖边', '热闹', '朋友聚会'],
   'facts_tags': [], 'risk_facts': ['夜间人多嘈杂'],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_friend_013'},
   'venue': {'environment': 'outdoor'}},

  {'poi_id': 'act_friend_014',
   'type': 'activity', 'scenario': 'friends',
   'name': '朝阳公园音乐节草坪（周末集市）',
   'category': 'outdoor_park',
   'address': '北京市朝阳区朝阳公园路',
   'distance_km': 9.0, 'open_status': 'open',
   'business_hours': '09:00-18:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 90,
   'rating': 4.4,
   'tags': ['户外', '集市', '文创', '打卡', '草坪', '周末'],
   'facts_tags': [], 'risk_facts': ['天气影响活动'],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_friend_014'},
   'venue': {'environment': 'outdoor'}},

  {'poi_id': 'act_friend_015',
   'type': 'activity', 'scenario': 'friends',
   'name': '前门大街历史文化步行游',
   'category': 'citywalk',
   'address': '北京市东城区前门大街',
   'distance_km': 14.0, 'open_status': 'open',
   'business_hours': '全天',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 80,
   'rating': 4.5,
   'tags': ['户外', '历史', '老北京', '小吃', 'Citywalk'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/citywalk/act_friend_015'},
   'venue': {'environment': 'outdoor'}},

  # ── Couple Activities 005-010 ──────────────────────────────────────
  {'poi_id': 'act_couple_005',
   'type': 'activity', 'scenario': 'couple',
   'name': '什刹海湖边骑行漫步',
   'category': 'outdoor_park',
   'address': '北京市西城区什刹海',
   'distance_km': 12.8, 'open_status': 'open',
   'business_hours': '全天',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 90,
   'rating': 4.7,
   'tags': ['户外', '湖景', '情侣', '骑行', '胡同', '浪漫'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_couple_005'},
   'venue': {'environment': 'outdoor'}},

  {'poi_id': 'act_couple_006',
   'type': 'activity', 'scenario': 'couple',
   'name': '颐和园昆明湖游船',
   'category': 'outdoor_park',
   'address': '北京市海淀区新建宫门路19号',
   'distance_km': 24.0, 'open_status': 'open',
   'business_hours': '06:30-18:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 150,
   'rating': 4.8,
   'tags': ['户外', '皇家园林', '游船', '情侣', '浪漫', '历史'],
   'facts_tags': [], 'risk_facts': ['较远，建议打车', '18点停止入园'],
   'external_entry': {'type': 'meituan_page', 'url': 'mock://meituan/activity/act_couple_006'},
   'venue': {'environment': 'outdoor'}},

  {'poi_id': 'act_couple_007',
   'type': 'activity', 'scenario': 'couple',
   'name': '圆明园遗址公园',
   'category': 'outdoor_park',
   'address': '北京市海淀区清华西路28号',
   'distance_km': 22.5, 'open_status': 'open',
   'business_hours': '07:00-20:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 120,
   'rating': 4.6,
   'tags': ['户外', '遗址', '历史', '情侣', '荷花', '安静'],
   'facts_tags': [], 'risk_facts': ['较远'],
   'external_entry': {'type': 'meituan_page', 'url': 'mock://meituan/activity/act_couple_007'},
   'venue': {'environment': 'outdoor'}},

  {'poi_id': 'act_couple_008',
   'type': 'activity', 'scenario': 'couple',
   'name': '三里屯太古里夜逛',
   'category': 'citywalk',
   'address': '北京市朝阳区三里屯路',
   'distance_km': 7.5, 'open_status': 'open',
   'business_hours': '10:00-23:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 80,
   'rating': 4.5,
   'tags': ['户外', '时尚', '情侣', '夜晚', '逛街', '网红'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/citywalk/act_couple_008'},
   'venue': {'environment': 'outdoor'}},

  {'poi_id': 'act_couple_009',
   'type': 'activity', 'scenario': 'couple',
   'name': '北京故宫护城河夕阳漫步',
   'category': 'citywalk',
   'address': '北京市东城区筒子河沿岸',
   'distance_km': 13.5, 'open_status': 'open',
   'business_hours': '全天',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 60,
   'rating': 4.8,
   'tags': ['户外', '情侣', '夕阳', '散步', '浪漫', '免费'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_couple_009'},
   'venue': {'environment': 'outdoor'}},

  {'poi_id': 'act_couple_010',
   'type': 'activity', 'scenario': 'couple',
   'name': '草莓音乐节（工体公园草坪）',
   'category': 'livehouse',
   'address': '北京市朝阳区工人体育场附近',
   'distance_km': 9.5, 'open_status': 'open',
   'business_hours': '14:00-22:00',
   'booking_required': True, 'availability': 'available',
   'available_slots': ['14:00', '18:00'],
   'estimated_duration_min': 120,
   'rating': 4.7,
   'tags': ['户外', '音乐', '情侣', '演出', '草坪', '浪漫'],
   'facts_tags': [], 'risk_facts': ['需提前购票'],
   'external_entry': {'type': 'ticket_page', 'url': 'mock://ticket/concert/act_couple_010'},
   'venue': {'environment': 'outdoor'},
   'activity_features': ['concert']},

  # ── Universal Activities 003-010 ───────────────────────────────────
  {'poi_id': 'act_both_003',
   'type': 'activity', 'scenario': 'both',
   'name': '北海公园游船+白塔',
   'category': 'outdoor_park',
   'address': '北京市西城区文津街1号',
   'distance_km': 13.0, 'open_status': 'open',
   'business_hours': '06:00-21:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 100,
   'rating': 4.7,
   'tags': ['户外', '皇家园林', '游船', '湖景', '全年龄', '历史'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_page', 'url': 'mock://meituan/activity/act_both_003'},
   'venue': {'environment': 'outdoor'}},

  {'poi_id': 'act_both_004',
   'type': 'activity', 'scenario': 'both',
   'name': '景山公园俯瞰故宫',
   'category': 'outdoor_park',
   'address': '北京市西城区景山前街44号',
   'distance_km': 13.5, 'open_status': 'open',
   'business_hours': '06:00-21:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 60,
   'rating': 4.7,
   'tags': ['户外', '俯瞰', '全景', '历史', '免费', '打卡'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_page', 'url': 'mock://meituan/activity/act_both_004'},
   'venue': {'environment': 'outdoor'}},

  {'poi_id': 'act_both_005',
   'type': 'activity', 'scenario': 'both',
   'name': '龙潭公园春游',
   'category': 'outdoor_park',
   'address': '北京市东城区龙潭路10号',
   'distance_km': 13.8, 'open_status': 'open',
   'business_hours': '06:00-21:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 80,
   'rating': 4.3,
   'tags': ['户外', '公园', '湖景', '散步', '全年龄', '免费'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_both_005'},
   'venue': {'environment': 'outdoor'}},

  {'poi_id': 'act_both_006',
   'type': 'activity', 'scenario': 'both',
   'name': '望京SOHO建筑打卡',
   'category': 'citywalk',
   'address': '北京市朝阳区望京街10号',
   'distance_km': 1.5, 'open_status': 'open',
   'business_hours': '全天',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 45,
   'rating': 4.4,
   'tags': ['户外', '建筑', '打卡', '网红', '免费', '近'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_both_006'},
   'venue': {'environment': 'outdoor'}},

  {'poi_id': 'act_both_007',
   'type': 'activity', 'scenario': 'both',
   'name': '五道营胡同文创市集',
   'category': 'citywalk',
   'address': '北京市东城区雍和宫附近五道营胡同',
   'distance_km': 11.5, 'open_status': 'open',
   'business_hours': '10:00-22:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 75,
   'rating': 4.6,
   'tags': ['户外', '胡同', '文创', '咖啡', '全年龄', 'Citywalk'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/citywalk/act_both_007'},
   'venue': {'environment': 'outdoor'}},

  {'poi_id': 'act_both_008',
   'type': 'activity', 'scenario': 'both',
   'name': '中国国家图书馆·古籍展览厅',
   'category': 'museum',
   'address': '北京市海淀区中关村南大街33号',
   'distance_km': 16.5, 'open_status': 'open',
   'business_hours': '09:00-17:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 80,
   'rating': 4.5,
   'tags': ['室内', '文化', '展览', '免费', '安静', '全年龄'],
   'facts_tags': [], 'risk_facts': ['17点闭馆'],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_both_008'},
   'venue': {'environment': 'indoor'}},

  # ═══════════════════ ADDITIONAL RESTAURANTS (50) ══════════════════

  # ── Family Restaurants 005-019 ─────────────────────────────────────
  {'poi_id': 'rest_family_005',
   'type': 'restaurant', 'scenario': 'family',
   'name': '西贝莜面村（望京店）',
   'category': 'restaurant',
   'address': '北京市朝阳区望京凯德MALL',
   'distance_km': 1.8,
   'cuisine': '西北菜',
   'avg_price': 100,
   'rating': 4.6,
   'tags': ['西北菜', '莜面', '亲子', '儿童椅', '大份量'],
   'booking_required': False,
   'available_slots': ['17:00', '18:00', '18:30'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_family_005'},
   'menu_features': ['low_oil_options'],
   'facilities': {'child_seat': True}},

  {'poi_id': 'rest_family_006',
   'type': 'restaurant', 'scenario': 'family',
   'name': '呷哺呷哺小火锅（望京店）',
   'category': 'restaurant',
   'address': '北京市朝阳区望京SOHO',
   'distance_km': 1.0,
   'cuisine': '火锅',
   'avg_price': 75,
   'rating': 4.3,
   'tags': ['小火锅', '亲子', '一人一锅', '卫生', '价格实惠'],
   'booking_required': False,
   'available_slots': ['17:00', '17:30', '18:00', '18:30'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_family_006'},
   'menu_features': ['light_food_options'],
   'facilities': {'child_seat': True}},

  {'poi_id': 'rest_family_007',
   'type': 'restaurant', 'scenario': 'family',
   'name': '金鼎轩老北京菜（望京店）',
   'category': 'restaurant',
   'address': '北京市朝阳区望京商圈',
   'distance_km': 2.5,
   'cuisine': '北京菜',
   'avg_price': 85,
   'rating': 4.4,
   'tags': ['老北京', '家常菜', '亲子', '大桌', '北京特色'],
   'booking_required': False,
   'available_slots': ['17:00', '17:30', '18:00'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_family_007'},
   'menu_features': ['low_oil_options'],
   'facilities': {'child_seat': True}},

  {'poi_id': 'rest_family_008',
   'type': 'restaurant', 'scenario': 'family',
   'name': '眉州东坡（望京店）',
   'category': 'restaurant',
   'address': '北京市朝阳区望京',
   'distance_km': 2.0,
   'cuisine': '川菜',
   'avg_price': 95,
   'rating': 4.5,
   'tags': ['川菜', '家常', '亲子友好', '儿童椅', '可微辣'],
   'booking_required': False,
   'available_slots': ['17:30', '18:00', '18:30', '19:00'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_family_008'},
   'menu_features': [],
   'facilities': {'child_seat': True}},

  {'poi_id': 'rest_family_009',
   'type': 'restaurant', 'scenario': 'family',
   'name': '东来顺涮羊肉（望京店）',
   'category': 'restaurant',
   'address': '北京市朝阳区望京商圈',
   'distance_km': 3.0,
   'cuisine': '涮羊肉',
   'avg_price': 120,
   'rating': 4.6,
   'tags': ['涮羊肉', '老字号', '亲子', '北京特色', '暖胃'],
   'booking_required': False,
   'available_slots': ['17:00', '17:30', '18:00'],
   'facts_tags': [], 'risk_facts': ['晚餐高峰期排队较长'],
   'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_family_009'},
   'menu_features': [],
   'facilities': {'child_seat': True}},

  {'poi_id': 'rest_family_010',
   'type': 'restaurant', 'scenario': 'family',
   'name': '云腾食府（云南菜）',
   'category': 'restaurant',
   'address': '北京市朝阳区望京北',
   'distance_km': 2.8,
   'cuisine': '云南菜',
   'avg_price': 90,
   'rating': 4.4,
   'tags': ['云南菜', '清淡', '适合儿童老人', '菌汤', '健康'],
   'booking_required': False,
   'available_slots': ['17:30', '18:00', '18:30'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_family_010'},
   'menu_features': ['low_oil_options'],
   'facilities': {'child_seat': True}},

  {'poi_id': 'rest_family_011',
   'type': 'restaurant', 'scenario': 'family',
   'name': '全聚德烤鸭（和平里店）',
   'category': 'restaurant',
   'address': '北京市东城区和平里北街18号',
   'distance_km': 8.5,
   'cuisine': '北京菜',
   'avg_price': 165,
   'rating': 4.6,
   'tags': ['烤鸭', '老字号', '亲子', '北京必吃', '适合全家'],
   'booking_required': True,
   'available_slots': ['17:30', '18:00', '18:30'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_reserve_page', 'url': 'mock://meituan/reserve/rest_family_011'},
   'menu_features': [],
   'facilities': {'child_seat': True}},

  {'poi_id': 'rest_family_012',
   'type': 'restaurant', 'scenario': 'family',
   'name': '望京小腰烧烤（望京店）',
   'category': 'restaurant',
   'address': '北京市朝阳区望京',
   'distance_km': 1.5,
   'cuisine': '烧烤',
   'avg_price': 80,
   'rating': 4.5,
   'tags': ['烧烤', '烤腰子', '亲子', '热闹', '夜宵'],
   'booking_required': False,
   'available_slots': ['17:30', '18:00', '18:30', '19:00'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_family_012'},
   'menu_features': [],
   'facilities': {'child_seat': False}},

  {'poi_id': 'rest_family_013',
   'type': 'restaurant', 'scenario': 'family',
   'name': '萨莉亚意大利餐厅（望京店）',
   'category': 'restaurant',
   'address': '北京市朝阳区望京凯德MALL',
   'distance_km': 1.8,
   'cuisine': '意大利菜',
   'avg_price': 60,
   'rating': 4.2,
   'tags': ['意大利', '亲子', '价格实惠', '儿童椅', '性价比高'],
   'booking_required': False,
   'available_slots': ['17:00', '17:30', '18:00', '18:30'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_family_013'},
   'menu_features': ['light_food_options'],
   'facilities': {'child_seat': True}},

  {'poi_id': 'rest_family_014',
   'type': 'restaurant', 'scenario': 'family',
   'name': '大食代美食广场（望京凯德）',
   'category': 'restaurant',
   'address': '北京市朝阳区望京凯德MALL负一层',
   'distance_km': 1.8,
   'cuisine': '多种选择',
   'avg_price': 50,
   'rating': 4.0,
   'tags': ['美食广场', '多种选择', '亲子', '儿童椅', '价格实惠'],
   'booking_required': False,
   'available_slots': ['11:00', '12:00', '17:00', '18:00'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/rest_family_014'},
   'menu_features': [],
   'facilities': {'child_seat': True}},

  {'poi_id': 'rest_family_015',
   'type': 'restaurant', 'scenario': 'family',
   'name': '胡大饭馆（号码牌·小龙虾）',
   'category': 'restaurant',
   'address': '北京市东城区簋街',
   'distance_km': 12.0,
   'cuisine': '川菜',
   'avg_price': 110,
   'rating': 4.6,
   'tags': ['小龙虾', '热辣', '亲子', '簋街必吃', '人气超旺'],
   'booking_required': False,
   'available_slots': ['17:00', '18:00'],
   'facts_tags': [], 'risk_facts': ['晚高峰等位时间长'],
   'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_family_015'},
   'menu_features': [],
   'facilities': {'child_seat': False}},

  # ── Friends Restaurants 005-019 ────────────────────────────────────
  {'poi_id': 'rest_friend_005',
   'type': 'restaurant', 'scenario': 'friends',
   'name': '大董烤鸭（现代京菜）',
   'category': 'restaurant',
   'address': '北京市朝阳区东大桥路8号楼',
   'distance_km': 9.5,
   'cuisine': '北京菜',
   'avg_price': 250,
   'rating': 4.8,
   'tags': ['烤鸭', '高端', '创意京菜', '打卡', '朋友聚会'],
   'booking_required': True,
   'available_slots': ['18:00', '18:30', '19:00'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_reserve_page', 'url': 'mock://meituan/reserve/rest_friend_005'},
   'menu_features': [],
   'facilities': {}},

  {'poi_id': 'rest_friend_006',
   'type': 'restaurant', 'scenario': 'friends',
   'name': '后海大排档（湖边夜宵）',
   'category': 'restaurant',
   'address': '北京市西城区后海北沿',
   'distance_km': 12.0,
   'cuisine': '烧烤/夜宵',
   'avg_price': 90,
   'rating': 4.4,
   'tags': ['夜宵', '大排档', '湖边', '热闹', '朋友聚餐'],
   'booking_required': False,
   'available_slots': ['17:00', '18:00', '19:00', '20:00'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_friend_006'},
   'menu_features': [],
   'facilities': {}},

  {'poi_id': 'rest_friend_007',
   'type': 'restaurant', 'scenario': 'friends',
   'name': '京兆尹素食餐厅（雍和宫附近）',
   'category': 'restaurant',
   'address': '北京市东城区雍和宫大街',
   'distance_km': 11.5,
   'cuisine': '素食',
   'avg_price': 180,
   'rating': 4.7,
   'tags': ['素食', '禅意', '高端', '朋友', '环境雅致', '需预约'],
   'booking_required': True,
   'available_slots': ['18:00', '18:30'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_reserve_page', 'url': 'mock://meituan/reserve/rest_friend_007'},
   'menu_features': ['light_food_options', 'low_oil_options'],
   'facilities': {}},

  {'poi_id': 'rest_friend_008',
   'type': 'restaurant', 'scenario': 'friends',
   'name': '胡桃里音乐餐厅（三里屯店）',
   'category': 'restaurant',
   'address': '北京市朝阳区三里屯附近',
   'distance_km': 7.5,
   'cuisine': '中西融合',
   'avg_price': 130,
   'rating': 4.5,
   'tags': ['音乐餐厅', '现场音乐', '朋友聚会', '氛围好', '适合夜晚'],
   'booking_required': True,
   'available_slots': ['18:00', '18:30', '19:00'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_reserve_page', 'url': 'mock://meituan/reserve/rest_friend_008'},
   'menu_features': [],
   'facilities': {}},

  {'poi_id': 'rest_friend_009',
   'type': 'restaurant', 'scenario': 'friends',
   'name': '黄记煌三汁焖锅（望京店）',
   'category': 'restaurant',
   'address': '北京市朝阳区望京商圈',
   'distance_km': 2.2,
   'cuisine': '焖锅',
   'avg_price': 95,
   'rating': 4.4,
   'tags': ['焖锅', '特色', '朋友聚餐', '无需排队', '香辣'],
   'booking_required': False,
   'available_slots': ['17:00', '17:30', '18:00', '18:30'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_friend_009'},
   'menu_features': [],
   'facilities': {}},

  {'poi_id': 'rest_friend_010',
   'type': 'restaurant', 'scenario': 'friends',
   'name': '朝阳大悦城·潮汕牛肉火锅',
   'category': 'restaurant',
   'address': '北京市朝阳区大悦城',
   'distance_km': 12.5,
   'cuisine': '潮汕火锅',
   'avg_price': 150,
   'rating': 4.8,
   'tags': ['火锅', '潮汕', '高口碑', '朋友聚餐', '人气高', '需预约'],
   'booking_required': True,
   'available_slots': ['18:00', '19:00'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_reserve_page', 'url': 'mock://meituan/reserve/rest_friend_010'},
   'menu_features': [],
   'facilities': {}},

  {'poi_id': 'rest_friend_011',
   'type': 'restaurant', 'scenario': 'friends',
   'name': '满记甜品（望京店）',
   'category': 'restaurant',
   'address': '北京市朝阳区望京SOHO',
   'distance_km': 1.0,
   'cuisine': '港式甜品',
   'avg_price': 55,
   'rating': 4.5,
   'tags': ['甜品', '港式', '下午茶', '朋友聚会', '芒果', '椰汁'],
   'booking_required': False,
   'available_slots': ['14:00', '15:00', '16:00', '17:00'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_friend_011'},
   'menu_features': ['light_food_options'],
   'facilities': {}},

  {'poi_id': 'rest_friend_012',
   'type': 'restaurant', 'scenario': 'friends',
   'name': '天秤座精酿酒吧（望京店）',
   'category': 'restaurant',
   'address': '北京市朝阳区望京商圈',
   'distance_km': 2.0,
   'cuisine': '酒吧/简餐',
   'avg_price': 120,
   'rating': 4.4,
   'tags': ['精酿啤酒', '朋友', '夜晚', '轻食', '氛围'],
   'booking_required': False,
   'available_slots': ['17:00', '18:00', '19:00', '20:00'],
   'facts_tags': [], 'risk_facts': ['需年满18周岁'],
   'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_friend_012'},
   'menu_features': [],
   'facilities': {}},

  {'poi_id': 'rest_friend_013',
   'type': 'restaurant', 'scenario': 'friends',
   'name': '利苑酒家（CBD店）',
   'category': 'restaurant',
   'address': '北京市朝阳区建国路万达广场',
   'distance_km': 11.0,
   'cuisine': '粤菜',
   'avg_price': 200,
   'rating': 4.7,
   'tags': ['粤菜', '高端', '点心', '朋友聚会', '需预约'],
   'booking_required': True,
   'available_slots': ['18:00', '18:30', '19:00'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_reserve_page', 'url': 'mock://meituan/reserve/rest_friend_013'},
   'menu_features': [],
   'facilities': {}},

  {'poi_id': 'rest_friend_014',
   'type': 'restaurant', 'scenario': 'friends',
   'name': '新麻辣烫（望京北店）',
   'category': 'restaurant',
   'address': '北京市朝阳区望京北',
   'distance_km': 1.8,
   'cuisine': '麻辣烫',
   'avg_price': 60,
   'rating': 4.3,
   'tags': ['麻辣烫', '自选', '价格实惠', '朋友', '快捷'],
   'booking_required': False,
   'available_slots': ['11:00', '17:00', '18:00'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_friend_014'},
   'menu_features': [],
   'facilities': {}},

  {'poi_id': 'rest_friend_015',
   'type': 'restaurant', 'scenario': 'friends',
   'name': '望京韩式BBQ自助烤肉',
   'category': 'restaurant',
   'address': '北京市朝阳区望京韩国城',
   'distance_km': 2.0,
   'cuisine': '韩式烤肉',
   'avg_price': 160,
   'rating': 4.5,
   'tags': ['自助烤肉', '韩料', '朋友聚会', '管够', '热闹'],
   'booking_required': False,
   'available_slots': ['17:30', '18:00', '18:30'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_friend_015'},
   'menu_features': [],
   'facilities': {}},

  # ── Couple Restaurants 004-013 ─────────────────────────────────────
  {'poi_id': 'rest_couple_004',
   'type': 'restaurant', 'scenario': 'couple',
   'name': '颐和园听鹂馆（宫廷菜）',
   'category': 'restaurant',
   'address': '北京市海淀区颐和园内',
   'distance_km': 24.0,
   'cuisine': '宫廷菜',
   'avg_price': 380,
   'rating': 4.7,
   'tags': ['宫廷菜', '浪漫', '园林环境', '情侣', '高端', '需预约'],
   'booking_required': True,
   'available_slots': ['17:30', '18:00'],
   'facts_tags': [], 'risk_facts': ['较远，建议打车前往'],
   'external_entry': {'type': 'meituan_reserve_page', 'url': 'mock://meituan/reserve/rest_couple_004'},
   'menu_features': [],
   'facilities': {}},

  {'poi_id': 'rest_couple_005',
   'type': 'restaurant', 'scenario': 'couple',
   'name': '北平机器（独特工业风）',
   'category': 'restaurant',
   'address': '北京市朝阳区工体北路',
   'distance_km': 9.0,
   'cuisine': '中西融合',
   'avg_price': 160,
   'rating': 4.6,
   'tags': ['工业风', '情侣', '打卡', '创意菜', '独特'],
   'booking_required': True,
   'available_slots': ['18:00', '18:30', '19:00'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_reserve_page', 'url': 'mock://meituan/reserve/rest_couple_005'},
   'menu_features': [],
   'facilities': {}},

  {'poi_id': 'rest_couple_006',
   'type': 'restaurant', 'scenario': 'couple',
   'name': '和平饭店·老上海厅',
   'category': 'restaurant',
   'address': '北京市东城区王府井',
   'distance_km': 13.0,
   'cuisine': '上海菜',
   'avg_price': 220,
   'rating': 4.6,
   'tags': ['上海菜', '复古', '情侣', '精致', '浪漫晚餐'],
   'booking_required': True,
   'available_slots': ['18:00', '18:30', '19:00'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_reserve_page', 'url': 'mock://meituan/reserve/rest_couple_006'},
   'menu_features': [],
   'facilities': {}},

  {'poi_id': 'rest_couple_007',
   'type': 'restaurant', 'scenario': 'couple',
   'name': '玉河畔庭院餐厅',
   'category': 'restaurant',
   'address': '北京市东城区玉河古道旁',
   'distance_km': 12.5,
   'cuisine': '中餐创意菜',
   'avg_price': 280,
   'rating': 4.8,
   'tags': ['庭院', '情侣', '浪漫', '创意菜', '私密', '需预约'],
   'booking_required': True,
   'available_slots': ['18:00', '19:00'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_reserve_page', 'url': 'mock://meituan/reserve/rest_couple_007'},
   'menu_features': [],
   'facilities': {}},

  {'poi_id': 'rest_couple_008',
   'type': 'restaurant', 'scenario': 'couple',
   'name': '忆江南私房菜（望京店）',
   'category': 'restaurant',
   'address': '北京市朝阳区望京',
   'distance_km': 2.5,
   'cuisine': '江南私房菜',
   'avg_price': 200,
   'rating': 4.7,
   'tags': ['私房菜', '情侣', '精致', '浪漫', '江南味道'],
   'booking_required': True,
   'available_slots': ['18:00', '18:30', '19:00'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_reserve_page', 'url': 'mock://meituan/reserve/rest_couple_008'},
   'menu_features': [],
   'facilities': {}},

  {'poi_id': 'rest_couple_009',
   'type': 'restaurant', 'scenario': 'couple',
   'name': '鱼酸·云南情调餐厅',
   'category': 'restaurant',
   'address': '北京市朝阳区望京西路',
   'distance_km': 3.0,
   'cuisine': '云南菜',
   'avg_price': 140,
   'rating': 4.6,
   'tags': ['云南菜', '情调', '情侣', '花卉装饰', '菌汤'],
   'booking_required': False,
   'available_slots': ['17:30', '18:00', '18:30'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_couple_009'},
   'menu_features': ['low_oil_options'],
   'facilities': {}},

  {'poi_id': 'rest_couple_010',
   'type': 'restaurant', 'scenario': 'couple',
   'name': '故宫角楼咖啡（文化创意园餐厅）',
   'category': 'restaurant',
   'address': '北京市东城区故宫周边',
   'distance_km': 14.0,
   'cuisine': '咖啡/轻食',
   'avg_price': 90,
   'rating': 4.7,
   'tags': ['咖啡', '打卡', '情侣', '下午茶', '文创', '故宫联名'],
   'booking_required': False,
   'available_slots': ['14:00', '15:00', '16:00', '17:00'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_couple_010'},
   'menu_features': ['light_food_options'],
   'facilities': {}},

  # ── Universal Restaurants 002-011 ─────────────────────────────────
  {'poi_id': 'rest_both_002',
   'type': 'restaurant', 'scenario': 'both',
   'name': '庆丰包子铺（王府井店）',
   'category': 'restaurant',
   'address': '北京市东城区王府井大街',
   'distance_km': 13.0,
   'cuisine': '北京小吃',
   'avg_price': 35,
   'rating': 4.3,
   'tags': ['包子', '老字号', '北京特色', '价格实惠', '快捷'],
   'booking_required': False,
   'available_slots': ['11:00', '12:00', '17:00', '18:00'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/rest_both_002'},
   'menu_features': [],
   'facilities': {'child_seat': False}},

  {'poi_id': 'rest_both_003',
   'type': 'restaurant', 'scenario': 'both',
   'name': '老北京炸酱面馆（望京店）',
   'category': 'restaurant',
   'address': '北京市朝阳区望京',
   'distance_km': 1.2,
   'cuisine': '北京菜',
   'avg_price': 45,
   'rating': 4.4,
   'tags': ['炸酱面', '老北京', '价格实惠', '快捷', '全年龄'],
   'booking_required': False,
   'available_slots': ['11:00', '12:00', '17:00', '18:00'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_both_003'},
   'menu_features': [],
   'facilities': {'child_seat': True}},

  {'poi_id': 'rest_both_004',
   'type': 'restaurant', 'scenario': 'both',
   'name': '兰州拉面大碗（望京店）',
   'category': 'restaurant',
   'address': '北京市朝阳区望京商圈',
   'distance_km': 0.8,
   'cuisine': '兰州拉面',
   'avg_price': 30,
   'rating': 4.1,
   'tags': ['拉面', '快捷', '价格实惠', '全年龄', '随便吃'],
   'booking_required': False,
   'available_slots': ['11:00', '12:00', '17:00', '18:00'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/rest_both_004'},
   'menu_features': [],
   'facilities': {'child_seat': False}},

  {'poi_id': 'rest_both_005',
   'type': 'restaurant', 'scenario': 'both',
   'name': '老鸭粉丝汤（望京店）',
   'category': 'restaurant',
   'address': '北京市朝阳区望京',
   'distance_km': 1.5,
   'cuisine': '汤锅',
   'avg_price': 50,
   'rating': 4.3,
   'tags': ['粉丝汤', '暖胃', '全年龄', '价格实惠', '健康'],
   'booking_required': False,
   'available_slots': ['11:00', '12:00', '17:00', '18:00'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_both_005'},
   'menu_features': ['low_oil_options'],
   'facilities': {'child_seat': True}},

  {'poi_id': 'rest_both_006',
   'type': 'restaurant', 'scenario': 'both',
   'name': '台湾卤肉饭小馆（望京店）',
   'category': 'restaurant',
   'address': '北京市朝阳区望京西路',
   'distance_km': 2.0,
   'cuisine': '台湾菜',
   'avg_price': 65,
   'rating': 4.5,
   'tags': ['卤肉饭', '台湾', '价格适中', '全年龄', '温馨'],
   'booking_required': False,
   'available_slots': ['11:30', '12:00', '17:30', '18:00'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_both_006'},
   'menu_features': [],
   'facilities': {'child_seat': True}},

  {'poi_id': 'rest_both_007',
   'type': 'restaurant', 'scenario': 'both',
   'name': '顺峰海鲜大酒楼（望京店）',
   'category': 'restaurant',
   'address': '北京市朝阳区望京商圈',
   'distance_km': 2.5,
   'cuisine': '粤菜/海鲜',
   'avg_price': 140,
   'rating': 4.5,
   'tags': ['粤菜', '海鲜', '大桌聚餐', '全年龄', '点心'],
   'booking_required': False,
   'available_slots': ['17:00', '17:30', '18:00', '18:30'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_both_007'},
   'menu_features': [],
   'facilities': {'child_seat': True}},

  {'poi_id': 'rest_both_008',
   'type': 'restaurant', 'scenario': 'both',
   'name': '嘉禾一品火锅',
   'category': 'restaurant',
   'address': '北京市朝阳区望京北路',
   'distance_km': 3.0,
   'cuisine': '火锅',
   'avg_price': 100,
   'rating': 4.4,
   'tags': ['火锅', '全年龄', '性价比高', '食材新鲜', '聚餐'],
   'booking_required': False,
   'available_slots': ['17:00', '17:30', '18:00', '18:30', '19:00'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_both_008'},
   'menu_features': [],
   'facilities': {'child_seat': True}},

  {'poi_id': 'rest_both_009',
   'type': 'restaurant', 'scenario': 'both',
   'name': '珍宝海蟹（望京店）',
   'category': 'restaurant',
   'address': '北京市朝阳区望京',
   'distance_km': 1.8,
   'cuisine': '海鲜',
   'avg_price': 120,
   'rating': 4.5,
   'tags': ['海鲜', '螃蟹', '全年龄', '食材好', '秋季必吃'],
   'booking_required': False,
   'available_slots': ['17:00', '17:30', '18:00'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_both_009'},
   'menu_features': [],
   'facilities': {'child_seat': True}},

  {'poi_id': 'rest_both_010',
   'type': 'restaurant', 'scenario': 'both',
   'name': '外婆家（望京凯德店）',
   'category': 'restaurant',
   'address': '北京市朝阳区望京凯德MALL',
   'distance_km': 1.8,
   'cuisine': '江浙菜',
   'avg_price': 80,
   'rating': 4.5,
   'tags': ['江浙菜', '清淡', '全年龄', '性价比高', '口味好'],
   'booking_required': False,
   'available_slots': ['17:00', '17:30', '18:00', '18:30'],
   'facts_tags': [], 'risk_facts': ['晚餐高峰排队约30分钟'],
   'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_both_010'},
   'menu_features': ['low_oil_options'],
   'facilities': {'child_seat': True}},

  {'poi_id': 'rest_both_011',
   'type': 'restaurant', 'scenario': 'both',
   'name': '木屋烧烤（望京店）',
   'category': 'restaurant',
   'address': '北京市朝阳区望京商圈',
   'distance_km': 2.2,
   'cuisine': '烧烤',
   'avg_price': 90,
   'rating': 4.3,
   'tags': ['烧烤', '聚餐', '全年龄', '品种多', '适合户外'],
   'booking_required': False,
   'available_slots': ['17:00', '18:00', '19:00'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/rest_both_011'},
   'menu_features': [],
   'facilities': {'child_seat': False}},

  # ═══════════════════ NEW: 10 KID-FRIENDLY ACTIVITIES ═════════════════

  {'poi_id': 'act_kid_001',
   'type': 'activity', 'scenario': 'family',
   'name': '乐高探索中心（朝阳大悦城）',
   'category': 'indoor_playground',
   'address': '北京市朝阳区朝阳北路101号朝阳大悦城',
   'distance_km': 7.5, 'open_status': 'open',
   'business_hours': '10:00-22:00',
   'booking_required': True, 'availability': 'available',
   'available_slots': ['10:00', '13:00', '15:00'],
   'estimated_duration_min': 120,
   'rating': 4.8,
   'tags': ['室内', '乐高', '亲子', '积木', '创意', '需预约'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_page', 'url': 'mock://meituan/activity/act_kid_001'},
   'venue': {'environment': 'indoor'},
   'age_policy': {'min_age': 3, 'max_age': 12}},

  {'poi_id': 'act_kid_002',
   'type': 'activity', 'scenario': 'family',
   'name': '小小工程师创客体验馆',
   'category': 'children_science',
   'address': '北京市朝阳区望京凯德MALL B1',
   'distance_km': 1.8, 'open_status': 'open',
   'business_hours': '10:00-21:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 90,
   'rating': 4.6,
   'tags': ['室内', '科技', '动手', '亲子', '机器人', '近'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_page', 'url': 'mock://meituan/activity/act_kid_002'},
   'venue': {'environment': 'indoor'},
   'age_policy': {'min_age': 4, 'max_age': 12}},

  {'poi_id': 'act_kid_003',
   'type': 'activity', 'scenario': 'family',
   'name': '宝贝运动星球亲子运动馆',
   'category': 'indoor_playground',
   'address': '北京市朝阳区望京SOHO周边',
   'distance_km': 2.3, 'open_status': 'open',
   'business_hours': '09:30-20:30',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 100,
   'rating': 4.5,
   'tags': ['室内', '亲子运动', '攀岩', '蹦床', '软体乐园', '近'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_queue_page', 'url': 'mock://meituan/queue/act_kid_003'},
   'venue': {'environment': 'indoor'},
   'age_policy': {'min_age': 3, 'max_age': 10}},

  {'poi_id': 'act_kid_004',
   'type': 'activity', 'scenario': 'family',
   'name': '儿童陶艺体验工坊（望京）',
   'category': 'indoor_playground',
   'address': '北京市朝阳区望京街区',
   'distance_km': 1.5, 'open_status': 'open',
   'business_hours': '10:00-19:00',
   'booking_required': True, 'availability': 'available',
   'available_slots': ['10:30', '14:00', '15:30'],
   'estimated_duration_min': 80,
   'rating': 4.7,
   'tags': ['室内', '陶艺', '手工', '亲子', '文艺', '近', '需预约'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_page', 'url': 'mock://meituan/activity/act_kid_004'},
   'venue': {'environment': 'indoor'},
   'age_policy': {'min_age': 4, 'max_age': 12}},

  {'poi_id': 'act_kid_005',
   'type': 'activity', 'scenario': 'family',
   'name': '爱达乐儿童成长中心',
   'category': 'indoor_playground',
   'address': '北京市朝阳区来福士购物中心',
   'distance_km': 4.5, 'open_status': 'open',
   'business_hours': '10:00-21:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 90,
   'rating': 4.4,
   'tags': ['室内', '亲子', '游乐', '成长', '综合', '无需预约'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_page', 'url': 'mock://meituan/activity/act_kid_005'},
   'venue': {'environment': 'indoor'},
   'age_policy': {'min_age': 2, 'max_age': 10}},

  {'poi_id': 'act_kid_006',
   'type': 'activity', 'scenario': 'family',
   'name': '机器人创客营（朝阳）',
   'category': 'children_science',
   'address': '北京市朝阳区朝阳门外大街',
   'distance_km': 9.5, 'open_status': 'open',
   'business_hours': '09:00-18:00',
   'booking_required': True, 'availability': 'available',
   'available_slots': ['10:00', '14:00'],
   'estimated_duration_min': 120,
   'rating': 4.8,
   'tags': ['室内', '机器人', '编程', '科技', '亲子', '需预约'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_page', 'url': 'mock://meituan/activity/act_kid_006'},
   'venue': {'environment': 'indoor'},
   'age_policy': {'min_age': 6, 'max_age': 14}},

  {'poi_id': 'act_kid_007',
   'type': 'activity', 'scenario': 'family',
   'name': '冰雪嘉年华儿童冰场（芳草地）',
   'category': 'indoor_playground',
   'address': '北京市朝阳区芳草地购物中心',
   'distance_km': 8.5, 'open_status': 'open',
   'business_hours': '10:00-22:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 90,
   'rating': 4.5,
   'tags': ['室内', '冰场', '溜冰', '亲子', '冰雪', '体验'],
   'facts_tags': [], 'risk_facts': ['需要穿戴护具'],
   'external_entry': {'type': 'meituan_page', 'url': 'mock://meituan/activity/act_kid_007'},
   'venue': {'environment': 'indoor'},
   'age_policy': {'min_age': 3, 'max_age': 14}},

  {'poi_id': 'act_kid_008',
   'type': 'activity', 'scenario': 'family',
   'name': '中国儿童中心·室外游乐场',
   'category': 'indoor_playground',
   'address': '北京市东城区工人体育场北路',
   'distance_km': 8.0, 'open_status': 'open',
   'business_hours': '09:00-17:30',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 100,
   'rating': 4.4,
   'tags': ['户外', '游乐', '亲子', '儿童', '大型滑梯', '免费'],
   'facts_tags': [], 'risk_facts': ['17:30闭园'],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_kid_008'},
   'venue': {'environment': 'outdoor'},
   'age_policy': {'min_age': 2, 'max_age': 12}},

  {'poi_id': 'act_kid_009',
   'type': 'activity', 'scenario': 'family',
   'name': '北京国际科学城小科学家馆',
   'category': 'children_science',
   'address': '北京市朝阳区望京科技园',
   'distance_km': 3.2, 'open_status': 'open',
   'business_hours': '09:30-17:00',
   'booking_required': True, 'availability': 'available',
   'available_slots': ['10:00', '13:30'],
   'estimated_duration_min': 110,
   'rating': 4.7,
   'tags': ['室内', '科普', '互动', '亲子', '实验', '需实名预约'],
   'facts_tags': [], 'risk_facts': ['17点闭馆'],
   'external_entry': {'type': 'wechat_official_account', 'url': 'mock://wechat/kxc/reservation'},
   'venue': {'environment': 'indoor'},
   'age_policy': {'min_age': 4, 'max_age': 14},
   'booking_requirements': ['real_name_required']},

  {'poi_id': 'act_kid_010',
   'type': 'activity', 'scenario': 'family',
   'name': '自然博物馆儿童探索厅',
   'category': 'children_science',
   'address': '北京市东城区天桥南大街126号（儿童馆区）',
   'distance_km': 9.0, 'open_status': 'open',
   'business_hours': '09:00-17:00',
   'booking_required': True, 'availability': 'available',
   'available_slots': ['09:30', '13:00'],
   'estimated_duration_min': 90,
   'rating': 4.6,
   'tags': ['室内', '自然', '恐龙', '科普', '亲子', '需实名预约'],
   'facts_tags': [], 'risk_facts': ['需实名预约', '17点闭馆'],
   'external_entry': {'type': 'wechat_official_account', 'url': 'mock://wechat/natural/reservation'},
   'venue': {'environment': 'indoor'},
   'age_policy': {'min_age': 3, 'max_age': 12},
   'booking_requirements': ['real_name_required']},

  # ═══════════════════ NEW: 10 PARKS ════════════════════════════════════

  {'poi_id': 'act_park_001',
   'type': 'activity', 'scenario': 'both',
   'name': '元大都城垣遗址公园',
   'category': 'outdoor_park',
   'address': '北京市朝阳区北三环中路',
   'distance_km': 6.5, 'open_status': 'open',
   'business_hours': '06:00-21:30',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 75,
   'rating': 4.4,
   'tags': ['户外', '遗址', '历史', '散步', '全年龄', '免费'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_park_001'},
   'venue': {'environment': 'outdoor'}},

  {'poi_id': 'act_park_002',
   'type': 'activity', 'scenario': 'both',
   'name': '将台湿地公园',
   'category': 'outdoor_park',
   'address': '北京市朝阳区将台路',
   'distance_km': 4.8, 'open_status': 'open',
   'business_hours': '06:00-20:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 70,
   'rating': 4.3,
   'tags': ['户外', '湿地', '生态', '散步', '鸟类', '免费', '近'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_park_002'},
   'venue': {'environment': 'outdoor'}},

  {'poi_id': 'act_park_003',
   'type': 'activity', 'scenario': 'both',
   'name': '太阳宫公园',
   'category': 'outdoor_park',
   'address': '北京市朝阳区太阳宫路',
   'distance_km': 4.0, 'open_status': 'open',
   'business_hours': '06:00-21:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 60,
   'rating': 4.3,
   'tags': ['户外', '公园', '亲子', '跑步', '免费', '近'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_park_003'},
   'venue': {'environment': 'outdoor'}},

  {'poi_id': 'act_park_004',
   'type': 'activity', 'scenario': 'both',
   'name': '奥林匹克森林公园（南园）',
   'category': 'outdoor_park',
   'address': '北京市朝阳区科荟南路',
   'distance_km': 9.5, 'open_status': 'open',
   'business_hours': '06:00-22:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 120,
   'rating': 4.7,
   'tags': ['户外', '奥森', '跑步', '骑行', '打卡', '全年龄', '免费'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_park_004'},
   'venue': {'environment': 'outdoor'}},

  {'poi_id': 'act_park_005',
   'type': 'activity', 'scenario': 'both',
   'name': '陶然亭公园',
   'category': 'outdoor_park',
   'address': '北京市西城区太平街19号',
   'distance_km': 14.0, 'open_status': 'open',
   'business_hours': '06:00-21:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 90,
   'rating': 4.4,
   'tags': ['户外', '湖景', '历史', '散步', '全年龄', '免费'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_park_005'},
   'venue': {'environment': 'outdoor'}},

  {'poi_id': 'act_park_006',
   'type': 'activity', 'scenario': 'both',
   'name': '望京公园（全景区漫步）',
   'category': 'outdoor_park',
   'address': '北京市朝阳区望京街道望京公园',
   'distance_km': 1.2, 'open_status': 'open',
   'business_hours': '06:00-21:30',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 60,
   'rating': 4.2,
   'tags': ['户外', '散步', '免费', '全年龄', '近', '溜娃'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_park_006'},
   'venue': {'environment': 'outdoor'}},

  {'poi_id': 'act_park_007',
   'type': 'activity', 'scenario': 'both',
   'name': '双秀公园',
   'category': 'outdoor_park',
   'address': '北京市西城区中关村南大街',
   'distance_km': 16.5, 'open_status': 'open',
   'business_hours': '06:00-20:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 60,
   'rating': 4.2,
   'tags': ['户外', '公园', '安静', '免费', '散步'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_park_007'},
   'venue': {'environment': 'outdoor'}},

  {'poi_id': 'act_park_008',
   'type': 'activity', 'scenario': 'both',
   'name': '朝阳公园（中心湖区）',
   'category': 'outdoor_park',
   'address': '北京市朝阳区朝阳公园路6号',
   'distance_km': 8.5, 'open_status': 'open',
   'business_hours': '06:00-22:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 100,
   'rating': 4.6,
   'tags': ['户外', '湖景', '骑行', '打卡', '全年龄', '大型公园'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_park_008'},
   'venue': {'environment': 'outdoor'}},

  {'poi_id': 'act_park_009',
   'type': 'activity', 'scenario': 'both',
   'name': '奥林匹克公园（北园湿地）',
   'category': 'outdoor_park',
   'address': '北京市朝阳区国家奥林匹克公园北区',
   'distance_km': 9.0, 'open_status': 'open',
   'business_hours': '06:00-22:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 90,
   'rating': 4.5,
   'tags': ['户外', '湿地', '鸟类', '奥运', '散步', '打卡'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_park_009'},
   'venue': {'environment': 'outdoor'}},

  {'poi_id': 'act_park_010',
   'type': 'activity', 'scenario': 'both',
   'name': '日坛公园',
   'category': 'outdoor_park',
   'address': '北京市朝阳区日坛北路',
   'distance_km': 7.5, 'open_status': 'open',
   'business_hours': '06:00-21:30',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 70,
   'rating': 4.3,
   'tags': ['户外', '历史', '文化', '散步', '古建', '免费'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_park_010'},
   'venue': {'environment': 'outdoor'}},

  # ═══════════════════ NEW: 20 MUSEUMS / EXHIBITIONS ════════════════════

  {'poi_id': 'act_museum_001',
   'type': 'activity', 'scenario': 'both',
   'name': '首都博物馆',
   'category': 'museum',
   'address': '北京市西城区复兴门外大街16号',
   'distance_km': 17.0, 'open_status': 'open',
   'business_hours': '09:00-17:00',
   'booking_required': True, 'availability': 'available',
   'available_slots': ['09:00', '10:00', '13:00'],
   'estimated_duration_min': 120,
   'rating': 4.8,
   'tags': ['室内', '博物馆', '北京历史', '文化', '需实名预约'],
   'facts_tags': ['文化', '历史'], 'risk_facts': ['需实名预约', '17点闭馆'],
   'external_entry': {'type': 'wechat_official_account', 'url': 'mock://wechat/capitalmuseum/reservation'},
   'venue': {'environment': 'indoor'},
   'booking_requirements': ['real_name_required']},

  {'poi_id': 'act_museum_002',
   'type': 'activity', 'scenario': 'both',
   'name': '中国美术馆',
   'category': 'museum',
   'address': '北京市东城区五四大街1号',
   'distance_km': 11.5, 'open_status': 'open',
   'business_hours': '09:00-17:00',
   'booking_required': True, 'availability': 'available',
   'available_slots': ['09:00', '10:00', '13:30'],
   'estimated_duration_min': 90,
   'rating': 4.7,
   'tags': ['室内', '美术馆', '当代艺术', '展览', '文化'],
   'facts_tags': ['文化'], 'risk_facts': ['需实名预约', '17点闭馆'],
   'external_entry': {'type': 'wechat_official_account', 'url': 'mock://wechat/namoc/reservation'},
   'venue': {'environment': 'indoor'},
   'booking_requirements': ['real_name_required']},

  {'poi_id': 'act_museum_003',
   'type': 'activity', 'scenario': 'both',
   'name': '北京自然历史博物馆',
   'category': 'museum',
   'address': '北京市东城区天桥南大街126号',
   'distance_km': 15.5, 'open_status': 'open',
   'business_hours': '09:00-17:00',
   'booking_required': True, 'availability': 'available',
   'available_slots': ['09:30', '13:00'],
   'estimated_duration_min': 110,
   'rating': 4.7,
   'tags': ['室内', '自然', '恐龙化石', '科普', '全年龄'],
   'facts_tags': [], 'risk_facts': ['需实名预约'],
   'external_entry': {'type': 'wechat_official_account', 'url': 'mock://wechat/bjnhm/reservation'},
   'venue': {'environment': 'indoor'},
   'booking_requirements': ['real_name_required']},

  {'poi_id': 'act_museum_004',
   'type': 'activity', 'scenario': 'both',
   'name': '中国地质博物馆',
   'category': 'museum',
   'address': '北京市西城区西四羊肉胡同15号',
   'distance_km': 16.0, 'open_status': 'open',
   'business_hours': '09:00-16:30',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 90,
   'rating': 4.5,
   'tags': ['室内', '地质', '矿石', '化石', '科普', '免费'],
   'facts_tags': [], 'risk_facts': ['16:30闭馆'],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_museum_004'},
   'venue': {'environment': 'indoor'}},

  {'poi_id': 'act_museum_005',
   'type': 'activity', 'scenario': 'both',
   'name': '中国电影博物馆',
   'category': 'museum',
   'address': '北京市朝阳区南影路9号',
   'distance_km': 6.8, 'open_status': 'open',
   'business_hours': '09:00-17:00',
   'booking_required': True, 'availability': 'available',
   'available_slots': ['09:30', '13:00', '15:00'],
   'estimated_duration_min': 100,
   'rating': 4.6,
   'tags': ['室内', '电影', '文化', '互动', '全年龄', '需预约'],
   'facts_tags': [], 'risk_facts': ['需实名预约'],
   'external_entry': {'type': 'wechat_official_account', 'url': 'mock://wechat/cmcb/reservation'},
   'venue': {'environment': 'indoor'},
   'booking_requirements': ['real_name_required']},

  {'poi_id': 'act_museum_006',
   'type': 'activity', 'scenario': 'both',
   'name': '中国非物质文化遗产馆',
   'category': 'museum',
   'address': '北京市朝阳区湖景东路9号',
   'distance_km': 8.5, 'open_status': 'open',
   'business_hours': '09:00-17:00',
   'booking_required': True, 'availability': 'available',
   'available_slots': ['09:30', '13:30'],
   'estimated_duration_min': 100,
   'rating': 4.7,
   'tags': ['室内', '非遗', '传统文化', '手工艺', '展览', '需预约'],
   'facts_tags': ['文化'], 'risk_facts': ['需实名预约'],
   'external_entry': {'type': 'wechat_official_account', 'url': 'mock://wechat/ichina/reservation'},
   'venue': {'environment': 'indoor'},
   'booking_requirements': ['real_name_required']},

  {'poi_id': 'act_museum_007',
   'type': 'activity', 'scenario': 'friends',
   'name': '红砖美术馆',
   'category': 'exhibition',
   'address': '北京市朝阳区酒仙桥路2号798艺术区',
   'distance_km': 12.5, 'open_status': 'open',
   'business_hours': '10:00-18:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 90,
   'rating': 4.8,
   'tags': ['室内', '当代艺术', '打卡', '文艺', '798', '网红'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_page', 'url': 'mock://meituan/exhibition/act_museum_007'},
   'venue': {'environment': 'indoor'},
   'activity_features': ['exhibition', 'contemporary_art']},

  {'poi_id': 'act_museum_008',
   'type': 'activity', 'scenario': 'friends',
   'name': '北京时代美术馆',
   'category': 'exhibition',
   'address': '北京市海淀区中关村大街27号',
   'distance_km': 8.0, 'open_status': 'open',
   'business_hours': '10:00-18:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 80,
   'rating': 4.6,
   'tags': ['室内', '美术馆', '当代艺术', '展览', '文艺'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_page', 'url': 'mock://meituan/exhibition/act_museum_008'},
   'venue': {'environment': 'indoor'},
   'activity_features': ['exhibition']},

  {'poi_id': 'act_museum_009',
   'type': 'activity', 'scenario': 'both',
   'name': '北京艺术博物馆（万寿寺）',
   'category': 'museum',
   'address': '北京市海淀区万寿寺路',
   'distance_km': 18.5, 'open_status': 'open',
   'business_hours': '09:00-16:30',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 80,
   'rating': 4.4,
   'tags': ['室内', '古建', '艺术', '文物', '历史', '安静'],
   'facts_tags': [], 'risk_facts': ['16:30闭馆'],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_museum_009'},
   'venue': {'environment': 'indoor'}},

  {'poi_id': 'act_museum_010',
   'type': 'activity', 'scenario': 'friends',
   'name': '北京当代艺术中心（望京）',
   'category': 'exhibition',
   'address': '北京市朝阳区望京商业区内',
   'distance_km': 2.8, 'open_status': 'open',
   'business_hours': '10:00-20:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 75,
   'rating': 4.5,
   'tags': ['室内', '当代艺术', '展览', '打卡', '文艺', '近'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_page', 'url': 'mock://meituan/exhibition/act_museum_010'},
   'venue': {'environment': 'indoor'},
   'activity_features': ['exhibition']},

  {'poi_id': 'act_museum_011',
   'type': 'activity', 'scenario': 'both',
   'name': '三联韬奋书店（美术馆店24小时）',
   'category': 'museum',
   'address': '北京市东城区美术馆东街22号',
   'distance_km': 11.5, 'open_status': 'open',
   'business_hours': '24小时',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 60,
   'rating': 4.7,
   'tags': ['室内', '书店', '文艺', '安静', '24小时', '打卡'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_museum_011'},
   'venue': {'environment': 'indoor'}},

  {'poi_id': 'act_museum_012',
   'type': 'activity', 'scenario': 'both',
   'name': '北京画廊中心（草场地）',
   'category': 'exhibition',
   'address': '北京市朝阳区草场地村',
   'distance_km': 9.0, 'open_status': 'open',
   'business_hours': '11:00-18:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 90,
   'rating': 4.6,
   'tags': ['室内', '当代艺术', '画廊', '打卡', '摄影', '文艺'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_museum_012'},
   'venue': {'environment': 'outdoor'},
   'activity_features': ['exhibition', 'photography']},

  {'poi_id': 'act_museum_013',
   'type': 'activity', 'scenario': 'family',
   'name': '中国妇女儿童博物馆',
   'category': 'museum',
   'address': '北京市朝阳区安定路17号',
   'distance_km': 6.5, 'open_status': 'open',
   'business_hours': '09:00-16:30',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 90,
   'rating': 4.4,
   'tags': ['室内', '儿童', '历史', '科普', '亲子', '免费'],
   'facts_tags': [], 'risk_facts': ['16:30闭馆'],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_museum_013'},
   'venue': {'environment': 'indoor'},
   'age_policy': {'min_age': 3, 'max_age': 14}},

  {'poi_id': 'act_museum_014',
   'type': 'activity', 'scenario': 'friends',
   'name': '尤伦斯当代艺术中心 UCCA 草场地馆',
   'category': 'exhibition',
   'address': '北京市朝阳区草场地红一号',
   'distance_km': 9.5, 'open_status': 'open',
   'business_hours': '10:00-19:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 100,
   'rating': 4.9,
   'tags': ['室内', '当代艺术', '打卡', '高端', '文艺', '草场地'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_page', 'url': 'mock://meituan/exhibition/act_museum_014'},
   'venue': {'environment': 'indoor'},
   'activity_features': ['exhibition', 'contemporary_art']},

  {'poi_id': 'act_museum_015',
   'type': 'activity', 'scenario': 'both',
   'name': '皮克斯梦工厂沉浸式特展',
   'category': 'exhibition',
   'address': '北京市朝阳区国贸商业区',
   'distance_km': 8.8, 'open_status': 'open',
   'business_hours': '10:00-21:00',
   'booking_required': True, 'availability': 'available',
   'available_slots': ['10:00', '13:00', '15:30', '18:00'],
   'estimated_duration_min': 90,
   'rating': 4.8,
   'tags': ['室内', '沉浸式', '互动', '打卡', '全年龄', '需购票'],
   'facts_tags': [], 'risk_facts': ['需提前购票'],
   'external_entry': {'type': 'ticket_page', 'url': 'mock://ticket/exhibition/act_museum_015'},
   'venue': {'environment': 'indoor'},
   'activity_features': ['exhibition', 'immersive']},

  {'poi_id': 'act_museum_016',
   'type': 'activity', 'scenario': 'both',
   'name': '北京天文馆（新馆）',
   'category': 'museum',
   'address': '北京市海淀区西直门外大街138号',
   'distance_km': 15.5, 'open_status': 'open',
   'business_hours': '09:30-16:30',
   'booking_required': True, 'availability': 'available',
   'available_slots': ['10:00', '13:30'],
   'estimated_duration_min': 100,
   'rating': 4.7,
   'tags': ['室内', '天文', '球幕影院', '科普', '宇宙', '需预约'],
   'facts_tags': [], 'risk_facts': ['16:30闭馆'],
   'external_entry': {'type': 'wechat_official_account', 'url': 'mock://wechat/bjplanetarium2/reservation'},
   'venue': {'environment': 'indoor'},
   'booking_requirements': ['real_name_required']},

  {'poi_id': 'act_museum_017',
   'type': 'activity', 'scenario': 'friends',
   'name': '北京服装学院美术馆',
   'category': 'exhibition',
   'address': '北京市朝阳区和平街北口',
   'distance_km': 7.0, 'open_status': 'open',
   'business_hours': '09:00-17:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 70,
   'rating': 4.4,
   'tags': ['室内', '时尚', '艺术', '展览', '文创', '文艺'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_museum_017'},
   'venue': {'environment': 'indoor'},
   'activity_features': ['exhibition']},

  {'poi_id': 'act_museum_018',
   'type': 'activity', 'scenario': 'both',
   'name': '中国汽车博物馆',
   'category': 'museum',
   'address': '北京市丰台区北京汽车博物馆路',
   'distance_km': 24.0, 'open_status': 'open',
   'business_hours': '09:00-17:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 120,
   'rating': 4.5,
   'tags': ['室内', '汽车', '历史', '互动', '科普', '较远'],
   'facts_tags': [], 'risk_facts': ['较远建议打车', '17点闭馆'],
   'external_entry': {'type': 'meituan_page', 'url': 'mock://meituan/activity/act_museum_018'},
   'venue': {'environment': 'indoor'}},

  {'poi_id': 'act_museum_019',
   'type': 'activity', 'scenario': 'both',
   'name': '北京中轴线博物馆（开放展区）',
   'category': 'museum',
   'address': '北京市东城区正阳门附近',
   'distance_km': 13.5, 'open_status': 'open',
   'business_hours': '09:00-17:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 80,
   'rating': 4.6,
   'tags': ['室内', '世界遗产', '中轴线', '历史', '文化', '免费展区'],
   'facts_tags': ['文化', '历史'], 'risk_facts': [],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_museum_019'},
   'venue': {'environment': 'indoor'}},

  {'poi_id': 'act_museum_020',
   'type': 'activity', 'scenario': 'friends',
   'name': '木木艺术社区（751D·PARK）',
   'category': 'exhibition',
   'address': '北京市朝阳区酒仙桥路4号751D·PARK',
   'distance_km': 11.5, 'open_status': 'open',
   'business_hours': '11:00-19:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 90,
   'rating': 4.8,
   'tags': ['室内', '当代艺术', '工业风', '打卡', '网红', '文艺'],
   'facts_tags': [], 'risk_facts': [],
   'external_entry': {'type': 'meituan_page', 'url': 'mock://meituan/exhibition/act_museum_020'},
   'venue': {'environment': 'indoor'},
   'activity_features': ['exhibition', 'contemporary_art']},

  # ═══════════════════ NEW: BARS AS ACTIVITY (Entertainment) ════════════
  # 酒吧同时属于娱乐活动，通过 search_activities 可搜索到

  {'poi_id': 'act_bar_001',
   'type': 'activity', 'scenario': 'friends',
   'name': '后海胡同清吧（历史风情）',
   'category': 'bar_entertainment',
   'address': '北京市西城区后海北沿街区',
   'distance_km': 12.5, 'open_status': 'open',
   'business_hours': '14:00-02:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 120,
   'rating': 4.6,
   'tags': ['室内', '酒吧', '清吧', '胡同风情', '湖景', '社交', '18岁+'],
   'facts_tags': [], 'risk_facts': ['需年满18周岁'],
   'external_entry': {'type': 'meituan_page', 'url': 'mock://meituan/activity/act_bar_001'},
   'venue': {'environment': 'indoor'},
   'age_restriction': 18},

  {'poi_id': 'act_bar_002',
   'type': 'activity', 'scenario': 'friends',
   'name': '三里屯酒吧街（工体北门区域）',
   'category': 'bar_entertainment',
   'address': '北京市朝阳区工体北路',
   'distance_km': 7.5, 'open_status': 'open',
   'business_hours': '18:00-03:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 150,
   'rating': 4.4,
   'tags': ['室内', '酒吧', '夜生活', '社交', '热闹', '18岁+'],
   'facts_tags': [], 'risk_facts': ['需年满18周岁', '夜间人多嘈杂'],
   'external_entry': {'type': 'map_page', 'url': 'mock://map/poi/act_bar_002'},
   'venue': {'environment': 'indoor'},
   'age_restriction': 18},

  {'poi_id': 'act_bar_003',
   'type': 'activity', 'scenario': 'couple',
   'name': '屋顶清吧·夜景鸡尾酒吧（望京）',
   'category': 'bar_entertainment',
   'address': '北京市朝阳区望京国际商业中心顶楼',
   'distance_km': 2.0, 'open_status': 'open',
   'business_hours': '16:00-02:00',
   'booking_required': False, 'availability': 'available',
   'available_slots': [],
   'estimated_duration_min': 120,
   'rating': 4.7,
   'tags': ['室内', '酒吧', '屋顶', '夜景', '鸡尾酒', '情侣', '近', '18岁+'],
   'facts_tags': [], 'risk_facts': ['需年满18周岁'],
   'external_entry': {'type': 'meituan_page', 'url': 'mock://meituan/activity/act_bar_003'},
   'venue': {'environment': 'indoor'},
   'age_restriction': 18},
]
