ROUTES = {('home_wangjing', 'act_family_001', 'taxi'): {'from': 'home_wangjing',
                                               'to': 'act_family_001',
                                               'mode': 'taxi',
                                               'distance_km': 2.8,
                                               'duration_min': 13,
                                               'walk_distance_m': 80,
                                               'traffic_level': 'normal',
                                               'source': 'mock_route'},
 ('act_family_001', 'rest_family_001', 'taxi'): {'from': 'act_family_001',
                                                 'to': 'rest_family_001',
                                                 'mode': 'taxi',
                                                 'distance_km': 0.9,
                                                 'duration_min': 8,
                                                 'walk_distance_m': 120,
                                                 'traffic_level': 'normal',
                                                 'source': 'mock_route'},
 ('home_wangjing', 'act_friend_004', 'taxi'): {'from': 'home_wangjing',
                                               'to': 'act_friend_004',
                                               'mode': 'taxi',
                                               'distance_km': 2.4,
                                               'duration_min': 12,
                                               'walk_distance_m': 60,
                                               'traffic_level': 'normal',
                                               'source': 'mock_route'},
 ('home_wangjing', 'act_friend_003', 'taxi'): {'from': 'home_wangjing',
                                               'to': 'act_friend_003',
                                               'mode': 'taxi',
                                               'distance_km': 10.6,
                                               'duration_min': 32,
                                               'walk_distance_m': 200,
                                               'traffic_level': 'normal',
                                               'source': 'mock_route'}}
